---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation NetApp XCP
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - title: Prise en main de XCP
    type: solutions
    entries:
    - title: En savoir plus sur XCP
      url: "/xcp-index.html"
    - title: Fonctionnalités d'extension XCP NFS
      url: "/xcp-nfs-add-ons.html"
    - title: Fonctions non prises en charge
      url: "/xcp-unsupported-features.html"
    - title: Configurations compatibles
      url: "/xcp-supported-configurations.html"
    - title: Ports utilisés par XCP
      url: "/xcp-ports-used.html"
  - title: Installer XCP
    entries:
    - title: Préparez l'installation de XCP
      url: "/xcp-install-xcp.html"
    - title: Préparation de Linux pour XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Préparation de Windows pour XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Préparer l'analyse des fichiers
      url: "/xcp-prepare-file-analytics.html"
    - title: Installer XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Installer XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Installez File Analytics for NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Installez File Analytics pour SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configurer XCP
    entries:
    - title: Configurez le fichier INI pour XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Réglage des performances
      url: "/xcp-performance-tuning.html"
    - title: Variable d'environnement
      url: "/xcp-environment-variable.html"
    - title: Configurez le connecteur POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configurer le connecteur HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configurer l'évolutivité horizontale sur plusieurs nœuds
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Configurer le connecteur S3
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Planification de la migration des données
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: Planification de la migration des données NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planification de la migration des données SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planifiez la migration des données HDFS
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Planifier à l'aide de File Analytics
      entries:
      - title: Planifiez votre migration des données
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Accédez à l'analyse des fichiers
        url: "/xcp-access-file-analytics.html"
      - title: Ajouter des serveurs de fichiers
        url: "/xcp-add-file-servers.html"
      - title: Exécuter une acquisition
        url: "/xcp-run-a-scan.html"
    - title: Filtres
      url: "/xcp-filters.html"
    - title: Connexion pour NFS et SMB (facultatif)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migrer des données
    entries:
    - title: Migrer des données NFS
      url: "/xcp-migrate-data.html"
    - title: Migrer les données SMB
      url: "/xcp-migrate-smb-data.html"
      entries:
      - title: Migration de flux de données de remplacement NTFS pour SMB
        url: "/xcp-smb-ads.html"
    - title: Migration des données HDFS
      url: "/xcp-migrate-hdfs-data.html"
    - title: Exécutez plusieurs travaux XCP sur le même hôte
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Autres fonctionnalités NFS
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Résoudre les problèmes
    entries:
    - title: Dépanner les erreurs XCP NFS
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Dépanner les erreurs SMB XCP
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Dépanner les erreurs d'analyse des fichiers XCP
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Mentions légales
    url: "/legal-notices.html"
