---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation NetApp XCP
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - title: Prise en main de XCP
    entries:
    - title: En savoir plus sur XCP
      url: "/xcp-index.html"
    - title: Fonctionnalités d'extension XCP NFS
      url: "/xcp-nfs-add-ons.html"
    - title: Fonctions non prises en charge
      url: "/xcp-unsupported-features.html"
    - title: Configurations compatibles
      url: "/xcp-supported-configurations.html"
    - title: Ports utilisés par XCP
      url: "/xcp-ports-used.html"
  - title: Installer XCP
    entries:
    - title: Préparez l'installation de XCP
      url: "/xcp-install-xcp.html"
    - title: Préparation de Linux pour XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Préparation de Windows pour XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Préparer l'analyse des fichiers
      url: "/xcp-prepare-file-analytics.html"
    - title: Installer XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Installer XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Installez File Analytics for NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Installez File Analytics pour SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configurer XCP
    entries:
    - title: Configurez le fichier INI pour XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Réglage des performances
      url: "/xcp-performance-tuning.html"
    - title: Variable d'environnement
      url: "/xcp-environment-variable.html"
    - title: Configurez le connecteur POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configurer le connecteur HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configurer l'évolutivité horizontale sur plusieurs nœuds
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Configurer le connecteur S3
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Planification de la migration des données
    entries:
    - title: Présentation
      url: "/xcp-plan-data-migration.html"
    - title: Planification de la migration des données NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planification de la migration des données SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planifiez la migration des données HDFS
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Planifier à l'aide de File Analytics
      entries:
      - title: Planifiez votre migration des données
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Accédez à l'analyse des fichiers
        url: "/xcp-access-file-analytics.html"
      - title: Ajouter des serveurs de fichiers
        url: "/xcp-add-file-servers.html"
      - title: Exécuter une acquisition
        url: "/xcp-run-a-scan.html"
    - title: Filtres
      url: "/xcp-filters.html"
    - title: Connexion pour NFS et SMB (facultatif)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migrer des données
    entries:
    - title: Migrer des données NFS
      url: "/xcp-migrate-data.html"
    - title: Migrer les données SMB
      url: "/xcp-migrate-smb-data.html"
    - title: Migration de flux de données NTFS alternatif pour SMB
      entries:
      - title: Migration de flux de données NTFS alternatif pour SMB
        url: "/xcp-smb-ads.html"
    - title: Migration des données HDFS
      url: "/xcp-migrate-hdfs-data.html"
    - title: Exécutez plusieurs travaux XCP sur le même hôte
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Autres fonctionnalités NFS
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Résoudre les problèmes
    entries:
    - title: Dépanner les erreurs XCP NFS
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Dépanner les erreurs SMB XCP
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Dépanner les erreurs d'analyse des fichiers XCP
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Référence XCP
    entries:
    - title: Présentation de la référence de commande XCP
      url: "/xcp-reference-overview.html"
    - title: Référence des commandes NFS
      entries:
      - title: aide
        url: "/xcp-nfs-reference-help.html"
      - title: afficher
        url: "/xcp-nfs-reference-show.html"
      - title: licence
        url: "/xcp-nfs-reference-license.html"
      - title: activer
        url: "/xcp-nfs-reference-activate.html"
      - title: numériser
        url: "/xcp-nfs-reference-scan.html"
      - title: copier
        url: "/xcp-nfs-reference-copy.html"
      - title: synchronisation
        url: "/xcp-nfs-reference-sync.html"
      - title: reprendre
        url: "/xcp-nfs-reference-resume.html"
      - title: la vérification
        url: "/xcp-nfs-reference-verify.html"
      - title: chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: chown
        url: "/xcp-nfs-reference-chown.html"
      - title: logdump
        url: "/xcp-nfs-reference-logdump.html"
      - title: supprimer
        url: "/xcp-nfs-reference-delete.html"
      - title: estimation
        url: "/xcp-nfs-reference-estimate.html"
      - title: suppression d'index
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: isync
        url: "/xcp-nfs-reference-isync.html"
    - title: Référence de commande SMB
      entries:
      - title: aide
        url: "/xcp-smb-reference-help.html"
      - title: afficher
        url: "/xcp-smb-reference-show.html"
      - title: licence
        url: "/xcp-smb-reference-license.html"
      - title: activer
        url: "/xcp-smb-reference-activate.html"
      - title: numériser
        url: "/xcp-smb-reference-scan.html"
      - title: copier
        url: "/xcp-smb-reference-copy.html"
      - title: synchronisation
        url: "/xcp-smb-reference-sync.html"
      - title: la vérification
        url: "/xcp-smb-reference-verify.html"
      - title: configurer
        url: "/xcp-smb-reference-configure.html"
      - title: écouter
        url: "/xcp-smb-reference-listen.html"
    - title: Cas d'utilisation de XCP
      entries:
      - title: Cas d'utilisation de XCP
        url: "/xcp-reference-use-cases.html"
    - title: Journalisation XCP
      entries:
      - title: Définissez l'option logConfig
        url: "/xcp-reference-logging-logconfig.html"
      - title: Définissez l'option eventlog
        url: "/xcp-reference-logging-eventlog.html"
      - title: Activez le client syslog
        url: "/xcp-reference-logging-syslog.html"
    - title: Journaux d'événements XCP
      entries:
      - title: Journaux d'événements NFS
        url: "/xcp-reference-event-logs-nfs.html"
      - title: Journaux d'événements SMB
        url: "/xcp-reference-event-logs-smb.html"
  - title: Mentions légales
    url: "/legal-notices.html"
