---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: 'Le connecteur POSIX permet à XCP d"accéder à tout système de fichiers monté sur Linux, tel que NFSv4, XFS et Veritas.' 
---
= Exécutez plusieurs travaux XCP sur le même hôte XCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
À partir de XCP 1.9.2, vous pouvez exécuter plusieurs travaux ou commandes XCP sur un seul hôte XCP, à condition que l'hôte dispose de ressources suffisantes pour chaque travail. Lorsque vous exécutez une commande qui prend en charge plusieurs travaux, XCP utilise une mémoire hôte minimale pour terminer le travail, ce qui crée la capacité d'exécuter des travaux supplémentaires sur la même configuration hôte.



== Configuration minimale requise

Pour chaque tâche XCP, vous devez prévoir jusqu'à 64 Go de mémoire hôte et huit cœurs pour les migrations de moyenne à grande échelle.


NOTE: L'exécution de plusieurs tâches XCP sur un même hôte n'est pas prise en charge pour la migration des données SMB.



== Journalisation

Par défaut, chaque travail XCP est consigné dans un fichier journal distinct qui est unique à l'ID du travail. Ce mécanisme de journalisation fonctionne bien lors de l'exécution de plusieurs tâches sur le même hôte individuel. NetApp ne recommande pas de modifier le `xcpLogConfig.Json` pour utiliser un seul fichier `xcp.log` Fichier permettant de consigner plusieurs travaux XCP s'exécutant en parallèle sur le même hôte.



== Commandes prises en charge

L'exécution de plusieurs travaux XCP sur un même hôte est prise en charge avec les commandes XCP suivantes :

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== Commandes non prises en charge

L'exécution de plusieurs travaux XCP sur le même hôte n'est pas prise en charge avec `sync` commande.
