---
sidebar: sidebar 
permalink: xcp-smb-reference-sync.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: Référence de commande « sync » SMB XCP 
---
= synchronisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le `sync` la commande recherche les modifications et les modifications dans les partages source et cible en parallèle et applique les actions appropriées à la cible pour s'assurer que la cible est identique à la source. Le `sync` la commande compare le contenu des données, les horodatages, les attributs de fichier, la propriété et les informations de sécurité.

.Syntaxe
[source, cli]
----
xcp sync \\<source SMB share> \\<IP address of SMB destination server>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====
Le tableau suivant répertorie la `sync` paramètres et leur description.

[cols="2*"]
|===
| Paramètre | Description 


| <<smb_sync_help,sync -h, --help>> | Afficher ce message d'aide et quitter. 


| <<sync -v>> | Augmentez la verbosité de débogage. 


| <<smb_sync_parallel,sync -parallèle  >> | Nombre de processus simultanés (par défaut : <cpu-count>). 


| <<smb_sync_match,sync -match  lt;filtre  gt;  | Traiter uniquement les fichiers et répertoires correspondant au filtre (voir `xcp help - match` pour plus de détails). 


| <<smb_sync_exclude,sync -exclude  lt;filtre  gt;  | Exclure uniquement les fichiers et répertoires dans le filtre. 


| <<sync -preserve-atime>> | Restaurer la date du dernier accès sur la source. 


| <<sync -noatime>> | Ne vérifiez pas le temps d'accès aux fichiers. 


| <<sync -nuit>> | Ne vérifiez pas l'heure de création du fichier. 


| <<sync -nomtime>> | Ne vérifiez pas l'heure de modification du fichier. (Cette option est obsolète. Le système Sync continuera à fonctionner sans cette option.) 


| <<sync -noattrs>> | Ne pas vérifier les attributs. 


| <<sync -noownership>> | Ne vérifiez pas la propriété. 


| <<sync_smb_atime,sync -atilewindow et lt;float> >> | Différence de temps d'accès acceptable, en secondes. 


| <<sync_smb_ctime,sync -ctimawindow et lt;float> >> | Différence de temps de création acceptable, en secondes. 


| <<sync_smb_mtime,sync -mtimewindow et lt;float> >> | Différence de temps de modification acceptable, en secondes, 


| <<sync_smb_acl,sync -acl>> | Copier les informations de sécurité. 


| <<sync_smb_acl,sync -fallback-user  >> | Utilisateur Active Directory ou utilisateur local (non-domaine) sur la machine cible pour recevoir les autorisations des utilisateurs de la machine source locale (non-domaine) (par exemple : domaine\administrateur). 


| <<sync_smb_acl,sync -fallback-group  >> | Groupe Active Directory ou groupe local (non-domaine) sur la machine cible pour recevoir les autorisations des groupes de machines sources locaux (non-domaine) (par exemple : domaine\administrateurs). 


| <<sync -l>> | Augmente les détails de sortie. 


| <<smb_sync_root,sync -root>> | Synchronisez les listes de contrôle d'accès pour le répertoire racine. 


| <<smb_sync_onlyacl,sync -onlyacl>> | Copiez uniquement les informations de sécurité. 


| <<smb_sync_aclverify,sync -aclverify{yes,no} >> | Fournir une option permettant d'inclure ou d'ignorer la vérification de l'ACL pendant l'opération de synchronisation de l'ACL. 


| <<smb_sync_bs,sync -bs et lt;n> >> | Taille de bloc en lecture/écriture (par défaut : 1M). 


| <<sync -ads>> | Utilisez le `sync` commande avec `-ads` Indicateur permettant d'analyser les modifications et modifications des flux de données secondaires dans le partage SMB source et cible. S'il y a des modifications, il applique la modification à la cible à
assurez-vous que la cible est identique à la source. 
|===


== sync -h, --help

Utilisez le `-h` et `–-help` paramètres avec le `sync` pour afficher des informations détaillées sur le `sync` commande

.Syntaxe
[source, cli]
----
xcp sync -–help
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp sync --help
usage: xcp sync [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve-atime] [-noatime] [-noctime] [-nomtime] [-noattrs] [-atimewindow <float>]
[-ctimewindow <float>] [-mtimewindow <float>] [-acl] [-fallback-user FALLBACK_USER] [-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-l] [-root]
[-noownership] [-onlyacl] [-aclverify {yes,no}] [-bs <n>] [-ads] source target

Note: ONTAP does not let a SMB client modify COMPRESSED or ENCRYPTED attributes. XCP sync will ignore these file attributes.

positional arguments:
   source
   target

optional arguments:
   -h, --help              show this help message and exit
   -v                      increase debug verbosity
   -parallel <n>           number of concurrent processes (default: <cpu-count>)
   -match <filter>         only process files and directories that match the filter (see `xcp help -match` for details)
   -exclude <filter>       Exclude files and directories that match the filter (see `xcp help -exclude` for details)
   -preserve-atime	       restore last accessed date on source
   -noatime                do not check file access time
   -noctime                do not check file creation time
   -nomtime                do not check file modification time
   -noattrs                do not check attributes
   -atimewindow <float>    acceptable access time difference in seconds
   -ctimewindow <float>    acceptable creation time difference in seconds
   -mtimewindow <float>    acceptable modification time difference in seconds
   -acl                    copy security information
   -fallback-user FALLBACK_USER
                           the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
   -fallback-group FALLBACK_GROUP
                           the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
   -loglevel <name>        option to set log levelfilter
   -l                      increase output detail
   -root                   sync acl for root directory
   -noownership            do not sync ownership
   -onlyacl                sync only acls
   -aclverify {yes,no}     choose whether you need to skip acl verification
   -bs <n>                 read/write block size for sync (default: 1M)
   -ads                    sync ntfs alternate data stream
----
====


== sync -v

Utilisez le `-v` paramètre avec le `sync` pour fournir des informations de débogage détaillées.

.Syntaxe
[source, cli]
----
xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\XCP>xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
ERROR failed to remove from target "assembly\GAC_32\Microsoft.CertificateServices.PKIClient.Cmdlets\v4.0_6.3.0.0 31bf3856ad364e35\p ki.psd1": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_tar shil\\assembly\\GAC_32\\Microsoft.CertificateServices.PKIClient.Cmdlets\\v4.0_6.3.0.0 31bf3856ad 364e35\\pki.psd1'
ERROR failed to remove from target "assembly\GAC_64\Microsoft.GroupPolicy.AdmTmplEditor\v4.0_6.3.0.0 31bf3856ad364e35\Microsoft.Gro upPolicy.AdmTmplEditor.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.
\vol_SMB_target_xxxxxx\\assembly\\GAC_64\\Microsoft.GroupPolicy.AdmTmplEditor\\v4.0_6.3.0.0 31bf 3856ad364e35\\Microsoft.GroupPolicy.AdmTmplEditor.dll'
1,933 scanned, 1,361 compared, 2 errors, 0 skipped, 0 copied, 1,120 removed, 5s ERROR failed to remove from target
"assembly\GAC_64\System.Printing\v4.0_4.0.0.0 31bf3856ad364e35\System.Printing.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
4\\System.Printing\\v4.0_4.0.0.0 31bf3856ad364e35\\System.Printing.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.PowerShell.Workflow.ServiceCore\v4.0_3.0.0.0 31bf3856ad364e35\Micro soft.PowerShell.Workflow.ServiceCore.dll": [Errno 13] Access is denied: '\\\\
\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.PowerShell.Workflow.ServiceCore\\v4
.0_3.0.0.0  31bf3856ad364e35\\Microsoft.PowerShell.Workflow.ServiceCore.dll' ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.RightsManagementServices.ServerManager.DeploymentPlugin\v4.0_6.3.0.0
31bf3856ad364e35\Microsoft.RightsManagementServices.ServerManager.Deploymen n.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination
server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.RightsManagementServices.ServerMana ger.DeploymentPlugin\\v4.0_6.3.0.0 31bf3856ad364e35\\Mic
.RightsManagementServices.ServerManager.DeploymentPlugin.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\Microsoft.WSMan.Management\v4.0_3.0.0.0 31bf3856ad364e35\Microsoft.WSMan.Mana gement.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_
_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.WSMan.Management\\v4.0_3.0.0.0 31bf3856ad364e35\\Microsof t.WSMan.Management.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\PresentationUI\v4.0_4.0.0.0 31bf3856ad364e35\PresentationUI.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
SIL\\PresentationUI\\v4.0_4.0.0.0 31bf3856ad364e35\\PresentationUI.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0 b77a5c561934e089\System.IO.Comp ression.FileSystem.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.71.5
_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\System.IO.Compression.FileSystem\\v4.0_4.0.0.0 b77a5c561 934e089\\System.IO.Compression.FileSystem.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IdentityModel.Selectors\v4.0_4.0.0.0 b77a5c561934e089\System.IdentityM odel.Selectors.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\v s_target_xxxxxx\\assembly\\GAC_MSIL\\System.IdentityModel.Selectors\\v4.0_4.0.0.0 b77a5c561934e0 89\\System.IdentityModel.Selectors.dll'
2,747 scanned, 2,675 compared, 9 errors, 0 skipped, 0 copied, 2,624 removed, 10s ERROR failed to remove from target
"assembly\GAC_MSIL\System.Web.DataVisualization\v4.0_4.0.0.0 31bf3856ad364e35\System.Web.DataVis ualization.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_c
rget_xxxxxx\\assembly\\GAC_MSIL\\System.Web.DataVisualization\\v4.0_4.0.0.0 31bf3856ad364e35\\Sy stem.Web.DataVisualization.dll'
cp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
2,831 scanned, 0 copied, 2,831 compared, 0 removed, 10 errors Total Time : 10s
STATUS : PASSED
----
====


== sync -<n> parallèle

Utilisez le `-parallel <n>` paramètre avec le `sync` Commande permettant de définir un nombre plus élevé ou inférieur de processus simultanés XCP. Le `sync -parallel <n>` la commande se synchronise avec le nombre de processus simultanés (par défaut : <cpu-count>).


NOTE: La valeur maximale pour n est 61.

.Syntaxe
[source, cli]
----
xcp sync -parallel <n>> \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -parallel 5 \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
658 scanned, 244 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 5s
658 scanned, 606 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
658 scanned, 658 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
Sending statistics...
----
====


== sync -match <filter>

Utilisez le `-match <filter>` paramètre avec le `sync` pour analyser l'arborescence source et cible et comparer uniquement les fichiers ou répertoires correspondant à l'argument de filtre. S'il y a des différences, la commande applique les actions requises sur la cible pour les garder synchronisées.

.Syntaxe
[source, cli]
----
xcp sync -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 10 compared, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== sync -exclude <filter>

Utilisez le `-exclude <filter>` paramètre avec le `sync` pour exclure uniquement les fichiers et répertoires du filtre.

.Syntaxe
[source, cli]
----
xcp sync -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -exclude "path('*Exceptions*')" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -exclude path('*Exceptions*') \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
451 scanned, 427 excluded, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== sync -preserve-atime

Utilisez le `-preserve-atime` paramètre avec le `sync` Commande permettant de réinitialiser « atime » à la valeur d'origine avant que XCP ne lise le fichier.

.Syntaxe
[source, cli]
----
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 4s
STATUS : PASSED
----
====


== sync -noatime

Utilisez le `-noatime` paramètre avec le `sync` commande permettant de synchroniser toutes les différences entre la source et la cible, à l'exclusion des fichiers qui n'ont que des différences dans le temps d'accès.

.Syntaxe
[source, cli]
----
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED

----
====


== sync -nuit

Utilisez le `-noctime` paramètre avec le `sync` commande permettant de synchroniser toutes les différences entre la source et la cible, à l'exclusion des fichiers qui n'ont que des différences dans l'heure de création.

.Syntaxe
[source, cli]
----
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -nomtime

Utilisez le `-nomtime` paramètre avec le `sync` commande permettant de synchroniser toutes les différences entre la source et la cible, à l'exclusion des fichiers qui n'ont que des différences dans le temps de modification. (Cette option est obsolète. Le `sync` l'exécution de la commande se poursuivra sans cette option.)

.Syntaxe
[source, cli]
----
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -noattrs

Utilisez le `-noattrs` paramètre avec le `sync` commande permettant de synchroniser toutes les différences entre la source et la cible, à l'exclusion des fichiers qui ne présentent que des différences dans les attributs de fichier. XCP copie un fichier uniquement s'il a un contenu différent (les ACL sont transférées).

.Syntaxe
[source, cli]
----
xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -noownership

Utilisez le `-noownership` paramètre avec le `sync` commande permettant de synchroniser toutes les différences entre la source et la cible, à l'exclusion des fichiers qui n'ont que des différences de propriété.

.Syntaxe
[source, cli]
----
xcp sync -noownership \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
>xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

      Truncated Output
302,909 scanned,    301,365 compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m46s
307,632	scanned,	303,530	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m51s
308,434	scanned,	305,462	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m56s
310,824	scanned,	307,328	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m1s
313,238	scanned,	310,083	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m6s
314,867	scanned,	313,407	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m11s
318,277	scanned,	315,856	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m17s
321,005	scanned,	318,384	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m22s
322,189	scanned,	321,863	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m27s
323,906	scanned,	323,906	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m29s

xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
323,906 scanned, 0 copied, 323,906 compared, 0 removed, 0 errors
Total Time : 10m29s
STATUS : PASSED
----
====


== sync -atitimewindow <float>

Utilisez le `-atimewindow <float>` paramètre avec le `sync` pour spécifier la différence acceptable, en secondes, pour l'heure d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents si la différence dans le temps est inférieure à <value>.

.Syntaxe
[source, cli]
----
xcp sync -atimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Dans l'exemple suivant, XCP accepte une différence d'un temps allant jusqu'à 10 minutes entre les fichiers source et de destination, et il ne met pas à jour l'heure sur la cible.

.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share

xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -ctitimewindow <float>

Utilisez le `-ctimewindow <float>` paramètre avec le `sync` pour spécifier la différence acceptable, en secondes, pour l'heure ctime d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents lorsque la différence en temps est inférieure à <value>.

.Syntaxe
[source, cli]
----
xcp sync -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Dans l'exemple suivant, XCP accepte une différence d'heure jusqu'à 10 minutes entre les fichiers source et de destination, et il ne met pas à jour l'heure sur la cible.

.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -mtimewindow <float>

Utilisez le `-mtimewindow <float>` paramètre avec le `sync` pour spécifier la différence acceptable, en secondes, pour l'heure mtime d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents lorsque la différence dans le temps est inférieure à <value>.

.Syntaxe
[source, cli]
----
xcp sync -mtimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors Total Time : 3s
STATUS : PASSED
----
====


== sync -acl -fallback-user <fallback_user> -fallback-group <fallback_group>

Utilisez le `-acl`, `-fallback-user` et `-fallback-group` paramètres avec le `sync` pour comparer les données et les informations de sécurité de la source avec la cible et appliquer les actions requises sur la cible. Le `-fallback-user` et `-fallback-group` Les options sont un utilisateur ou un groupe sur la machine cible ou dans Active Directory qui reçoit les autorisations des utilisateurs ou groupes sources locaux (non-domaine).


NOTE: Vous ne pouvez pas utiliser `-acl` sans le `-fallback-user` et `-fallback-group` options.

.Syntaxe
[source, cli]
----
xcp sync -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\performance_SMB_home_dirs \\<IP address of SMB destination server>\performance_SMB_home_dirs
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
10,796	scanned,	4,002	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	s
15,796	scanned,	8,038	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,505	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,707	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,730	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,749	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,765	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,786	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,956	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,320	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	9,339	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,363	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	m0s
15,796	scanned,	10,019	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m5s
15,796	scanned,	10,042	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m10s
15,796	scanned,	10,059	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m15s
15,796	scanned,	10,075	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m20s
15,796	scanned,	10,091	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m25s
15,796	scanned,	10,108	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m30s
15,796	scanned,	10,929	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m35s
15,796	scanned,	12,443	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m40s
15,796	scanned,	13,963	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m45s
15,796	scanned,	15,488	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m50s
15,796	scanned,	15,796	compared,	0	errors,	0	skipped,     0	copied	0	removed,	1m51s

xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
15,796 scanned, 0 copied, 15,796 compared, 0 removed, 0 errors
Total Time : 1m51
STATUS : PASSED
----
====


== sync -l

Utilisez le `-l` paramètre avec le `sync` Commande permettant de fournir des informations de journalisation détaillées dans la sortie standard pour toutes les actions effectuées par XCP sur la cible.

.Syntaxe
[source, cli]
----
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

File "atime" changed, timestamps set for "agnostic"
File "atime" changed, timestamps set for "<root>"
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== sync -root

Utilisez le `-root` paramètre avec le `sync` Commande permettant de synchroniser les ACL du répertoire racine.

.Syntaxe
[source, cli]
----
xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
12 scanned, 0 copied, 12 compared, 0 skipped, 0 removed, 0 errors, 1 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== sync -onlyacl-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilisez le `-onlyacl`, `-fallback-user`, et `-fallback-group` paramètres avec le `sync` pour comparer les informations de sécurité entre la source et la cible et appliquer les actions requises sur la cible. Le `-fallback-user` et `-fallback-group` Sont un utilisateur ou un groupe sur la machine cible ou dans Active Directory qui reçoivent les autorisations des utilisateurs ou groupes sources locaux (non-domaine).


NOTE: Vous ne pouvez pas utiliser `-onlyacl` paramètre sans `-fallback-user` et `-fallback-group` options.

.Syntaxe
[source, cli]
----
xcp sync -onlyacl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\Users\ctladmin\Desktop>xcp sync -onlyacl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

8,814 scanned,	0	copied,	620	compared,	0	skipped,	0	removed,	0	errors,	6s
9,294 scanned,	0	copied,	2,064	compared,	0	skipped,	0	removed,	0	errors,	11s
12,614 scanned,	0	copied,	3,729	compared,	0	skipped,	0	removed,	0	errors,	16s
13,034 scanned,	0	copied,	5,136	compared,	0	skipped,	0	removed,	0	errors,	21s
14,282 scanned,	0	copied,	7,241	compared,	0	skipped,	0	removed,	0	errors,	26s
14,282 scanned,	0	copied,	8,101	compared,	0	skipped,	0	removed,	0	errors,	31s
14,282 scanned,	0	copied,	8,801	compared,	0	skipped,	0	removed,	0	errors,	36s
14,282 scanned,	0	copied,	9,681	compared,	0	skipped,	0	removed,	0	errors,	41s
14,282 scanned,	0	copied,	10,405	compared,	0	skipped,	0	removed,	0	errors,	46s
14,282 scanned,	0	copied,	11,431	compared,	0	skipped,	0	removed,	0	errors,	51s
14,282 scanned,	0	copied,	12,471	compared,	0	skipped,	0	removed,	0	errors,	56s
14,282 scanned,	0	copied,	13,495	compared,	0	skipped,	0	removed,	0	errors,	1m1s
14,282 scanned,	0	copied,	14,282	compared,	0	skipped,	0	removed,	0	errors,	1m6s

xcp sync -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
14,282 scanned, 0 copied, 14,282 compared, 0 skipped, 0 removed, 0 errors
Total Time : 1m7s
STATUS : PASSED

----
====


== sync -aclverify{yes,no}

Utilisez le `-aclverify{yes,no}` paramètre avec le `sync` Commande permettant de fournir une option permettant d'inclure ou d'ignorer la vérification de l'ACL pendant l'opération de synchronisation de l'ACL. Cette option ne peut être utilisée qu'avec `sync -acl` et `sync -onlyacl` commandes. La synchronisation ACL effectue la vérification ACL par défaut. Si vous définissez le `-aclverify` option à `no`, Vous pouvez ignorer la vérification ACL et `fallback-user` et `fallback-group` les options ne sont pas obligatoires. Si vous avez défini `-aclverify` à `yes`, il requiert le `fallback-user` et `fallback-group` options, comme illustré dans l'exemple suivant.

.Syntaxe
[source, cli]
----
xcp sync -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
25 scanned, 1 copied, 25 compared, 0 skipped, 0 removed, 0 errors, 12 acls copied Total Time : 16s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
27 scanned, 1 copied, 27 compared, 0 skipped, 0 removed, 0 errors, 13 acls copied Total Time : 2s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
C:\NetApp\xcp>xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 11 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== sync -bs <n>

Utilisez le `-bs <n>` paramètre avec le `sync` pour fournir une taille de bloc en lecture/écriture. La taille par défaut est 1M.

.Syntaxe
[source, cli]
----
xcp.exe sync -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
1,136 scanned, 0 copied, 1,135 compared, 0 skipped, 95 removed, 0 errors, 5s
xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share 1,136 scanned, 283 copied, 1,136 compared, 0 skipped, 283 removed, 0 errors
Total Time : 10s
STATUS : PASSED
----
====


== sync -ads

Utiliser `-ads` paramètre avec le `sync` Commande permettant d'analyser les modifications apportées aux autres flux de données dans le partage SMB source et cible. En cas de modifications, il applique la modification à la cible pour s'assurer que la cible est identique à la source.

.Syntaxe
[source, cli]
----
xcp sync -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	15s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	20s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	25s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	30s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	1m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m50s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m5s, 1 ads copied
xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_addess>\dest_share
13 scanned, 1 copied, 13 compared, 0 skipped, 0 removed, 0 errors, 1 ads copied
Total Time : 6m9s
STATUS : PASSED
----
====