---
sidebar: sidebar 
permalink: xcp-plan-nfs-data-migration.html 
keywords: netapp, xcp, plan, planning, data, migration, migrate, migrating, nfs, smb, file, analytics 
summary: Planification des migrations de données NFS 
---
= Planification de la migration des données NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Planifier les migrations de données NFS.



== Afficher

Le `show` Commande interroge les services RPC et les exportations NFS d'un ou plusieurs serveurs de stockage. La commande répertorie les services et exportations disponibles avec la capacité utilisée et libre de chaque exportation, suivie des attributs racine de chaque exportation. Exemple :

* `xcp show <NFS file server IP/FQDN>`
* `xcp show nfs_server01.netapp.com`


Courez `xcp help show` pour en savoir plus.



== Analyser

Le `scan` La commande analyse de manière récursive l'ensemble des chemins exportés par NFSv3 source et imprime les statistiques de la structure de fichiers à la fin de l'analyse. NetApp recommande de placer les montages d'exportation NFS source en mode lecture seule pendant l'analyse. Exemple :

* `xcp scan NFS [server:/export path | \file://<NFS mounted path> | hdfs://<hdfs mounted path> ]`
* `xcp scan nfs_server01.netapp.com:/export1`
* `xcp scan \file:///mnt/nfs-source`
* `xcp scan hdfs:///demo/user1`


Courez `xcp help scan` pour en savoir plus.

Vous pouvez également utiliser File Analytics pour afficher les résultats sous forme graphique.
