---
sidebar: sidebar 
permalink: xcp-smb-reference-verify.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: Référence de commande « vérification » SMB XCP 
---
= la vérification
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le `verify` cette commande lit et compare les partages source et cible et fournit des informations sur les différences. Vous pouvez utiliser le `verify` sur n'importe quelle source et destination, quel que soit l'outil utilisé pour effectuer l'opération de copie ou de synchronisation.

.Syntaxe
[source, cli]
----
xcp verify \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
xcp verify  \\<IP address of SMB source server>\source_share  \\ <IP address of SMB destination server>\dest_share

xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
Total Time : 3s
STATUS : PASSED
----
====
Le tableau suivant répertorie la `verify` paramètres et leur description.

[cols="2*"]
|===
| Paramètre | Description 


| <<smb_verify_help,vérifiez -h, --help>> | Afficher ce message d'aide et quitter. 


| <<vérifier -v>> | Augmentez la verbosité de débogage. 


| <<smb_verify_parallel,vérifier -parallèle  >> | Nombre de processus simultanés (par défaut : <cpu-count>). 


| <<smb_verify_match,vérifier -match  lt;filtre  gt;  | Traiter uniquement les fichiers et répertoires correspondant au filtre (voir `xcp help - match` pour plus de détails). 


| <<smb_verify_exclude,vérifier -exclure  gt;  | Exclure uniquement les fichiers et répertoires dans le filtre. 


| <<vérifiez -preserve-atime>> | Restaurer la date du dernier accès sur la source. 


| <<vérifiez -nodata>> | Ne vérifiez pas les données. 


| <<vérifiez -atime>> | Vérifiez l'heure d'accès aux fichiers. 


| <<vérifiez -nuit>> | Ne vérifiez pas l'heure de création du fichier. 


| <<vérifier -nomtime>> | Ne vérifiez pas l'heure de modification du fichier. 


| <<vérifiez -noattrs>> | Ne pas vérifier les attributs. 


| <<vérifier -noownership>> | Ne vérifiez pas la propriété. 


| <<vérifier -ads>> | La `verify` commande associée au `-ads` paramètre recherche tout autre flux de données sur la source et la destination et affiche les différences éventuelles. 


| <<vérifiez -noacls>> | Ne vérifiez pas les listes de contrôle d'accès. 


| <<verify_smb_atime,vérifier -atilewindow et lt;float> >> | Différence de temps d'accès acceptable, en secondes. 


| <<verify_smb_ctime,vérifier -ctimawindow et lt;float> >> | Différence de temps de création acceptable, en secondes. 


| <<verify_smb_mtime,vérifier -mtimewindow et lt;float> >> | Différence de temps de modification acceptable, en secondes, 


| <<vérifier -stats>> | Analysez les arborescences source et cible en parallèle et comparez les statistiques de l'arborescence. 


| <<vérifier -l>> | Augmente les détails de sortie. 


| <<vérifiez -ll>> | Augmente les détails de sortie (format Git diff). 


| <<verify_smb_acl,vérifier -fallback-user  >> | Utilisateur Active Directory ou utilisateur local (non-domaine) sur la machine cible pour recevoir les autorisations des utilisateurs de la machine source locale (non-domaine) (par exemple : domaine\administrateur). 


| <<verify_smb_acl,vérifier -fallback-group  >> | Groupe Active Directory ou groupe local (non-domaine) sur la machine cible pour recevoir les autorisations des groupes de machines sources locaux (non-domaine) (par exemple : domaine\administrateurs). 


| <<smb_verify_root,vérifiez -root>> | Vérifiez les listes de contrôle d'accès pour le répertoire racine. 


| <<verify_smb_onlyacl,vérifier -onlyacl>> | Vérifiez uniquement les informations de sécurité. 
|===


== vérifiez -h, --help

Utilisez le `-h` et `–-help` paramètres avec le `verify` pour afficher des informations détaillées sur le `verify` commande

.Syntaxe
[source, cli]
----
xcp verify –help
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp verify –help
usage: xcp verify [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>][-preserve-atime]
[-loglevel <name>] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-noacls] [-nodata] [-stats] [-l] [-root] [-noownership] [-onlyacl] [-noctime] [-nomtime] [-noattrs] [-atime]
[-atimewindow <float>] [-ctimewindow <float>] [-mtimewindow <float>] [-ads] source target

Note: ONTAP does not let a SMB client modify COMPRESSED or ENCRYPTED attributes. XCP sync will ignore these file attributes.

positional arguments:
   source
   target

optional arguments:
-h, --help	           show this help message and exit
-v	                    increase debug verbosity
-parallel <n>	        number of concurrent processes (default: <cpu-count>)
-match <filter>        only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>      Exclude files and directories that match the filter (see `xcp help -exclude` for details)
-preserve-atime	     restore last accessed date on source
--help-diag           Show all options including diag.The diag options should be used only on recommendation by NetApp support.
-loglevel <name>	     option to set log level filter (default:INFO)
-fallback-user FALLBACK_USER
                       a user on the target machine to translate the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                       a group on the target machine to translate the permissions of local (non- domain) source machine groups (eg. domain\administrators)
-nodata	              do not check data
-stats	              scan source and target trees in parallel and compare tree statistics
-l	                    detailed file listing output
-root	                 verify acl for root directory
-noacls	              do not check acls
-noownership	        do not check ownership
-onlyacl	              verify only acls
-noctime	              do not check file creation time
-nomtime	              do not check file modification time
-noattrs	              do not check attributes
-atime	              verify acess time as well
-atimewindow <float>   acceptable access time difference in seconds
-ctimewindow <float>   acceptable creation time difference in seconds
-mtimewindow <float>   acceptable modification time difference in seconds
-ads	                 verify ntfs alternate data stream
----
====


== vérifier -v

Utilisez le `-v` paramètre avec le `verify` pour fournir des informations de débogage détaillées.

.Syntaxe
[source, cli]
----
xcp verify -v \\<IP address of SMB source server>\source_share address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp> xcp verify -v \\<IP address of SMB source server>\source_share address of SMB destination server>\dest_share
xcp verify -v  \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v \\< IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -<n> parallèle

Utilisez le `-parallel <n>` paramètre avec le `verify` Commande permettant de définir un nombre plus élevé ou inférieur de processus simultanés XCP. Le `verify -parallel <n>` vérifie le nombre de processus simultanés (par défaut : <cpu-count>).


NOTE: La valeur maximale pour n est 61.

.Syntaxe
[source, cli]
----
xcp verify -v -parallel <n> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 4s
STATUS : PASSED
----
====


== vérifiez -match <filter>

Utilisez le `-match <filter>` paramètre avec le `verify` pour analyser l'arborescence source et cible et comparer uniquement les fichiers ou répertoires correspondant à l'argument de filtre. S'il y a des différences, la commande applique les actions requises sur la cible pour les garder synchronisées.

.Syntaxe
[source, cli]
----
xcp verify -v -match <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -v -match "'Microsoft' in name" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -v -match "'Microsoft' in name" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v -match 'Microsoft' in name \\<IP address of SMB source server> \source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 0 compared, 0 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== vérifier -exclure <filter>

Utilisez le `-exclude <filter>` paramètre avec le `verify` pour exclure uniquement les fichiers et répertoires du filtre.

.Syntaxe
[source, cli]
----
xcp verify -exclude <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp verify -exclude "path('*Exceptions*')" \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share

210 scanned, 99 excluded, 6 compared, 5 same, 1 different, 0 missing, 0 errors, 5s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 10s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 15s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 20s
335 scanned, 253 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 25s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 30s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 35s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 40s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 45s
445 scanned, 427 excluded, 16 compared, 15 same, 1 different, 0 missing, 0 errors, 50s
xcp verify -exclude path('*Exceptions*') \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
445 scanned, 427 excluded, 17 compared, 17 same, 0 different, 0 missing, 0 errors
Total Time : 1m11s
STATUS : PASSED
----
====


== vérifiez -preserve-atime

Utilisez le `-preserve-atime` paramètre avec le `verify` commande de réinitialisation `atime` À la valeur d'origine avant que XCP ne lise le fichier.

.Syntaxe
[source, cli]
----
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

374 scanned, 179 compared, 179 same, 0 different, 0 missing, 0 errors, 5s
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 8s
STATUS : PASSED
----
====


== vérifiez -nodata

Utilisez le `-nodata` paramètre avec le `verify` pour ne pas comparer les données.

.Syntaxe
[source, cli]
----
xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -nodata \\<IP address of SMB source server> \source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifiez -atime

Utilisez le `-atime` paramètre avec le `verify` commande permettant de comparer les horodatages d'accès aux fichiers de la source à la destination.

.Syntaxe
[source, cli]
----
xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\Netapp\xcp> xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

WARNING: your license will expire in less than one week! You can renew your license at https://xcp.netapp.com
dir1: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.564423)
     + 2023-04-14 10:24:40 (1681482280.366317)
dir2: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.564424)
     + 2023-04-14 10:24:40 (1681482280.366318)
<root>: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.054403)
     + 2023-04-14 10:28:35 (1681482515.538801)
xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
14 scanned, 13 compared, 10 same, 3 different, 0 missing, 0 errors
Total Time : 1s
STATUS : FAILED
----
====


== vérifiez -nuit

Utilisez le `-noctime` paramètre avec le `verify` commande permettant de ne pas comparer les horodatages de création de fichier de la source à la destination.

.Syntaxe
[source, cli]
----
xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -nomtime

Utilisez le `-nomtime` paramètre avec le `verify` commande permettant de ne pas comparer les horodatages de modification de fichier de la source à la destination.

.Syntaxe
[source, cli]
----
xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifiez -noattrs

Utilisez le `-noattrs` paramètre avec le `verify` pour ne pas vérifier les attributs.

.Syntaxe
[source, cli]
----
xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -noownership

Utilisez le `-noownership` paramètre avec le `verify` pour ne pas vérifier la propriété.

.Syntaxe
[source, cli]
----
xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noownership	\\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -ads

Utilisez le `-ads` paramètre avec la `verify` commande pour vérifier s'il existe d'autres flux de données sur la source et la destination et afficher les différences éventuelles.

.Syntaxe
[source, cli]
----
xcp verify -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	10s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	1m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	1m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	4m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m10s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	8m0s

xcp verify -ads \\source_Ip_address>\source_share\src \\<dest_IP_address>\dest_share
7 scanned, 6 compared, 6 same, 0 different, 0 missing, 0 errors
Total Time : 8m4s
STATUS : PASSED
----
====


== vérifiez -noacls

Utilisez le `-noacls` paramètre avec le `verify` Commande permettant de ne pas vérifier les ACL.

.Syntaxe
[source, cli]
----
xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noacls -noownership	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
318 scanned, 317 compared, 317 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


=== vérifiez -noacls -noownership

Utilisez le `-noownership` paramètre avec `verify -noacls`  Pour ne pas vérifier les ACL ou la propriété de la source vers la destination.

.Syntaxe
[source, cli]
----
xcp verify -noacls -noownership <source> <target>
----


== vérifiez -atitimewindow <float>

Utilisez le `-atimewindow <float>` paramètre avec le `verify` pour spécifier la différence acceptable, en secondes, pour le `atime` d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents si la différence dans `atime` est inférieur à <value>. Le `verify - atimewindow` la commande ne peut être utilisée qu'avec `-atime` drapeau.

.Syntaxe
[source, cli]
----
xcp verify -atimewindow <float> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\Netapp\xcp> xcp verify -atimewindow 600 -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -atimewindow 600 -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

14 scanned, 13 compared, 13 same, 0 different, 0 missing, 0 errors
----
====


== vérifier -ctitimewindow <float>

Utilisez le `-ctimewindow <float>` paramètre avec le `verify` pour spécifier la différence acceptable, en secondes, pour le `ctime` d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents lorsque la différence dans `ctime` est inférieur à <value>.

.Syntaxe
[source, cli]
----
xcp verify -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ctimewindow 600 \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -ctimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -ctimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -mtimewindow <float>

Utilisez le `-mtimewindow <float>` paramètre avec le `verify` pour spécifier la différence acceptable, en secondes, pour le `mtime` d'un fichier de la source à la destination. XCP ne signale pas que les fichiers sont différents lorsque la différence dans `mtime` est inférieur à <value>.

.Syntaxe
[source, cli]
----
xcp verify -mtimewindow <float> \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -mtimewindow 600 \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -mtimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -mtimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifier -stats

Utilisez le `-stats` paramètre avec le `verify` commande permettant de scanner la source et la destination et d'imprimer un rapport de statistiques d'arborescence indiquant les similitudes ou les différences entre les deux partages.

.Syntaxe
[source, cli]
----
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

       == Number of files ==
	            empty    <8KiB    8-64KiB    64KiB-1MiB   1-10MiB   10-100MiB   >100MiB
                               81        170            62         2
on-target                    same       same          same      same
on-source                    same       same          same      same

       == Directory entries ==
	            empty	  1-10     10-100	     100-1K	   1K-10K	     >10K
        		                       1             1
on-target                                same          same
on-source			             same	      same

       == Depth ==
                  0-5	  6-10	    11-15	      16-20	   21-100	     >100
	              317
on-target           same
on-source	      same

       == Modified ==
              >1 year	>1 month  1-31 days    1-24 hrs   <1 hour   <15 mins     future    invalid
                  315                                    2
on-target        same                                 same
on-source        same                                 same

Total count: 317 / same / same
Directories: 2 / same / same
Regular files: 315 / same / same
Symbolic links:
Junctions:
Special files:
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
635 scanned, 0 errors Total Time : 1s
STATUS : PASSED
----
====


== vérifier -l

Utilisez le `-l` paramètre avec le `verify` pour répertorier les différences entre les fichiers et les répertoires sur la source et la destination.

.Syntaxe
[source, cli]
----
xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
Dans l'exemple suivant, pendant la copie, les informations de propriété n'ont pas été transférées et vous pouvez voir les différences dans la sortie de la commande.

.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== vérifiez -ll

Utilisez le `-ll` paramètre avec le `verify` pour répertorier les différences détaillées entre les fichiers ou répertoires de la source et de la cible. Le format est comme git diff. La valeur rouge est l'ancienne valeur de la source et la valeur verte est la nouvelle valeur de la cible.

.Syntaxe
[source, cli]
----
xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== <fallback_group> verify-fallback-user <fallback_user> -fallback-group

Utilisez le `-fallback-user` et `-fallback-group` paramètres avec le `verify` Pour lister les ACL et les différences de propriété entre les fichiers et les répertoires sur la source et la destination.


NOTE: Si vous utilisez `fallback-user` et `fallback-group` Lors d'une opération de copie ou de synchronisation, NetApp vous recommande d'utiliser également le `fallback-user` et `fallback-group` paramètres avec l'opération de vérification.

.Syntaxe
[source, cli]
----
xcp verify -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


=== vérifiez -noownership-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilisez le `-noownership,` `-fallback-user`, et `-fallback-group` paramètres avec le `verify` Pour lister les différences de LCA et ignorer la vérification de propriété entre les fichiers et les répertoires de la source et de la destination.

.Syntaxe
[source, cli]
----
xcp verify -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


=== vérifiez -noacls-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilisez le `-noacls`, `-fallback-user`, et `-fallback-group` paramètres avec le `verify` Commande permettant d'ignorer la vérification des ACL et de vérifier la propriété entre les fichiers et les répertoires de la source et de la destination.

.Syntaxe
[source, cli]
----
xcp verify -noacls -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


== vérifiez -root

Utilisez le `-root` paramètre associé à la `verify` commande pour vérifier les ACL du répertoire racine.

.Syntaxe
[source, cli]
----
xcp verify -root -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp verify -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -l -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
7 scanned, 6 compared, 6 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


=== vérifiez -onlyacl -fallback-user <fallback_user> -fallback- group <fallback_group>

Utilisez le `-onlyacl`, `-fallback-user` et `-fallback-group` paramètres avec le `verify` pour comparer uniquement les informations de sécurité entre la source et la destination.

.Syntaxe
[source, cli]
----
xcp verify -onlyacl -preserve-atime -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
C:\Users\ctladmin\Desktop>xcp verify -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback- group "DOMAIN\Group" -ll \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

4,722	scanned,	0 compared, 0 same, 0 different, 0 missing, 0 errors, 5s
7,142	scanned,	120 compared, 120 same, 0 different, 0 missing, 0 errors, 10s
7,142	scanned,	856 compared, 856 same, 0 different, 0 missing, 0 errors, 15s
7,142	scanned,	1,374 compared, 1,374 same, 0 different, 0 missing, 0 errors,	20s
7,142	scanned,	2,168 compared, 2,168 same, 0 different, 0 missing, 0 errors,	25s
7,142	scanned,	2,910 compared, 2,910 same, 0 different, 0 missing, 0 errors,	30s
7,142	scanned,	3,629 compared, 3,629 same, 0 different, 0 missing, 0 errors,	35s
7,142	scanned,	4,190 compared, 4,190 same, 0 different, 0 missing, 0 errors,	40s
7,142	scanned,	4,842 compared, 4,842 same, 0 different, 0 missing, 0 errors,	45s
7,142	scanned,	5,622 compared, 5,622 same, 0 different, 0 missing, 0 errors,	50s
7,142	scanned,	6,402 compared, 6,402 same, 0 different, 0 missing, 0 errors,	55s
7,142	scanned,	7,019 compared, 7,019 same, 0 different, 0 missing, 0 errors,	1m0s

xcp verify -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" -ll \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
7,142 scanned, 7,141 compared, 7,141 same, 0 different, 0 missing, 0 errors
Total Time : 1m2s
STATUS : PASSED
----
====