---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: Installez ou mettez à niveau File Analytics pour NFS 
---
= Installez File Analytics for NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installez ou mettez à niveau File Analytics pour NFS.

.Description de la tâche
Pour connaître la configuration système requise pour NFS, reportez-vous à la section link:xcp-install-xcp-nfs.html["Installer XCP NFS"].

Le `configure.sh` Script installe XCP File Analytics sur une machine hôte Red Hat Enterprise Linux (RHEL). Dans le cadre de l'installation, le script installe la base de données Postgres, le serveur HTTPD Apache et les autres modules requis sur la machine Linux hôte. Pour plus d'informations sur les versions RHEL spécifiques prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["IMT"^]. Vous pouvez modifier ou mettre à jour une version plus récente en fonction de vos besoins et respecter les consignes de sécurité. Pour en savoir plus sur le `configure.sh` script, exécution `./configure.sh -h` sur la ligne de commande.

.Avant de commencer
* Si des opérations XCP sont en cours d'exécution, NetApp vous recommande de les exécuter avant de commencer la configuration.
* Votre ordinateur Linux doit être connecté au serveur de référentiel Yum ou à Internet.
* Si un pare-feu est configuré sur la machine Linux, vous devez modifier les paramètres du pare-feu pour activer le port 5030, qui est utilisé par le service XCP.


.Étapes
. Installez ou mettez à niveau File Analytics pour NFS.
+
[role="tabbed-block"]
====
.Installez File Analytics
--
.. Accédez au `xcp` et exécutez `./configure.sh` script.
+
Si l'installation réussit, le message suivant s'affiche :

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: Vous pouvez utiliser ce nom d'utilisateur et ce mot de passe pour vous connecter à l'interface graphique de File Analytics.



--
.Mettez à niveau l'analytique de fichiers
--
.. Accédez au `xcp` dossier et exécution `./configure.sh -f`.
.. À l'invite, entrez `y` pour nettoyer et reconfigurer le système.
+
Une fois le script approuvé, il nettoie la configuration existante et reconfigure le système.

+
Si le message suivant s'affiche, le message suivant s'affiche :

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. Lancez l'analyse de fichiers dans un navigateur pris en charge : *adresse \https://<ip de linux>/xcp*.
+
Reportez-vous à la section link:xcp-install-xcp-nfs.html["Installer XCP NFS"] pour plus d'informations sur les navigateurs pris en charge.


