---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: Migrer des données 
---
= Migrer des données NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après avoir planifié la migration avec `show` et `scan` Vous pouvez migrer les données NFS.



== Copier

Le `copy` La commande analyse et copie l'ensemble de la structure du répertoire source dans une exportation NFSv3 de destination. Le `copy` la commande nécessite l'utilisation de chemins source et de destination comme variables. Les fichiers numérisés et copiés, le débit/la vitesse et le temps écoulé sont affichés à la fin de l'opération de copie.

*Exemple:*

[listing]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
*Exemple de chemin POSIX :*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
Courez `xcp help copy` pour en savoir plus.



== Reprendre

Le `resume` la commande redémarre une opération de copie interrompue précédemment en spécifiant le nom ou le numéro d'index du catalogue. Le nom d'index de catalogue ou le numéro de l'opération de copie précédente est stocké sur le `<catalog path>:/catalog/indexes` répertoire.

*Exemple:*

[listing]
----
xcp resume -id <catalog_name>
----
Courez `xcp help resume` pour en savoir plus.



== Synchrone

Le `sync` La commande recherche les modifications et modifications effectuées sur un répertoire NFS source à l'aide d'un nom de repère d'indexation de catalogue ou du numéro d'une opération de copie précédente. Les modifications incrémentielles source sont copiées et appliquées au répertoire cible. Les anciens numéros d'index de catalogue sont remplacés par un nouveau [.souligné]#après l'opération de synchronisation#.

*Exemple:*

[listing]
----
xcp sync -id <catalog_name>
----
Courez `xcp help sync` pour en savoir plus.



== La vérification

Le `verify` la commande utilise une comparaison complète des données octet par octet entre les répertoires source et cible après l'opération de copie sans utiliser de numéro d'index de catalogue. La commande recherche les heures de modification et d'autres attributs de fichier ou de répertoire, y compris les autorisations. La commande lit également les fichiers des deux côtés et compare les données.

*Exemple:*

[listing]
----
xcp verify <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol
----
*Exemple de chemin POSIX :*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
Courez `xcp help verify` pour en savoir plus.



== ISync

Le `isync` la commande compare la source et la destination et synchronise les différences sur la cible sans utiliser l'index du catalogue.

*Exemple*

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
Vous pouvez utiliser `isync` avec le `estimate` option permettant d'estimer le temps nécessaire pour le `isync` pour synchroniser les modifications incrémentielles. Le `-id` paramètre spécifie le nom de catalogue d'une opération de copie précédente.


NOTE: Si vous modifiez plus de 25 % de la taille du jeu de données utilisé, le `isync estimate` il se peut que la commande n'affiche pas les résultats attendus.

*Exemple*

[listing]
----
xcp isync estimate -id <name>
----
Courez `xcp help isync` pour en savoir plus.
