---
sidebar: sidebar 
permalink: xcp-nfs-reference-scan.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Référence de commande XCP NFS 
---
= numériser
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le NFS XCP `scan` La commande analyse de manière récursive l'ensemble des chemins d'accès exportés par NFSv3 source et renvoie les statistiques de structure de fichiers.

NetApp vous recommande de placer les montages d'exportation NFS source en mode lecture seule pendant l'opération d'analyse.

.Syntaxe
[source, cli]
----
xcp scan <source_nfs_export_path>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan <IP address of NFS server>:/

source_vol
source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan <IP address of NFS server>:/source vol
----
====
Le tableau suivant répertorie la `scan` paramètres et leur description.

[cols="2*"]
|===
| Paramètre | Description 


| <<scan_l,balayage -l>> | Répertorie les fichiers au format de sortie de la liste longue. 


| <<scan_q,scan -q>> | Affiche le nombre de fichiers analysés. 


| <<nfs_scan_stats_csv_html,scannez -stats>> | Répertorie les fichiers au format de rapport statistique de l'arborescence. 


| <<nfs_scan_stats_csv_html,scan -csv>> | Répertorie les fichiers au format de rapport CSV statistique de l'arborescence. 


| <<nfs_scan_stats_csv_html,scan -html>> | Répertorie les fichiers au format de rapport HTML des statistiques de l'arborescence. 


| <<scan -non-ames>> | Exclut les noms d'utilisateur et de groupe des listes de fichiers et des rapports. 


| <<nfs_scan_newid,scan -newid  >> | Spécifie le nom du catalogue pour un nouvel index. 


| <<nfs_scan_id,scan -id  >> | Indique le nom du catalogue d'une copie ou d'un index de numérisation précédent. 


| <<nfs_scan_match,balayage - correspondance  lt;filtre  gt;  | Traite uniquement les fichiers et répertoires correspondant au filtre. 


| <<nfs_scan_fmt,scan -fmt  >> | Traite uniquement les fichiers et répertoires qui correspondent au format. 


| <<nfs_scan_du,scan -du>> | Récapitule l'utilisation de l'espace de chaque répertoire, y compris les sous-répertoires. 


| <<nfs_scan_md5,scan -md5  >> | Génère des sommes de contrôle sur les fichiers et enregistre les sommes de contrôle lors de l'indexation (valeur par défaut : FALSE). 


| <<nfs_scan_depth,balayage - profondeur  lt;n>  | Limite la profondeur de recherche. 


| <<nfs_scan_dircount,scan -dircount  lt;n[k]>  | Spécifie la taille de la demande lors de la lecture des répertoires. 


| <<nfs_scan_edupe,scan -edupe>> | Inclut l'estimation de la déduplication dans les rapports. 


| <<nfs_scan_bs,scan -bs [k]>  | Spécifie la taille des blocs de lecture/écriture pour les analyses qui lisent des données à l'aide de `-md5` ou `-edupe` (par défaut : 64 ko). 


| <<nfs_scan_parallel,balayage - parallèle et gauche ; n ;  | Spécifie le nombre maximal de processus de traitement par lots simultanés (par défaut : 7). 


| <<nfs_scan_noid,Scan -noid >> | Désactive la création d'un index par défaut (par défaut : FALSE). 


| <<nfs_scan_subdir,scan -subdir-names>> | Récupère les noms des sous-répertoires de niveau supérieur dans un répertoire. 


| <<scan -preserve-atime>> | Restaure tous les fichiers à la dernière date d'accès sur la source. 


| <<acquisition -s3.insecure>> | Permet d'utiliser HTTP au lieu de HTTPS pour les communications entre compartiments S3. 


| <<nfs_scan_endpoint,scan -s3.endpoint  >> | Remplace l'URL du terminal Amazon Web Services (AWS) par défaut par l'URL spécifiée pour la communication du compartiment S3. 


| <<nfs_scan_s3_profile,scan -s3.profile  >> | Spécifie un profil à partir du fichier d'informations d'identification AWS pour la communication du compartiment S3. 


| <<acquisition -s3.noverify>> | Remplace la vérification par défaut de la certification SSL pour les communications de compartiment S3. 
|===


== balayage -l

Utilisez le `-l` paramètre avec le `scan` commande permettant de répertorier les fichiers au format de sortie de la liste longue.

.Syntaxe
[source, cli]
----
xcp scan -l <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -l <IP address or hostname of NFSserver>:/source_vol

drwxr-xr-x --- root root 4KiB 4KiB 6s source_vol
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.1
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42ssource_vol/USER.1/FILE_4
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_4
Xcp command : xcp scan -l <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.89 KiB/s), 756 out (989/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -q

Utilisez le `-q` paramètre avec le `scan` pour afficher le nombre de fichiers analysés.

.Syntaxe
[source, cli]
----
xcp scan -q <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -q <IP address or hostname of NFSserver>:/source_vol

Xcp command : xcp scan -q <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (3.96 KiB/s), 756 out(801/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -stats, scan -csv et scan -html

Utilisez le `-stats`, `-csv`, et `-html` paramètres avec le `scan` commande permettant de répertorier les fichiers au format de rapport statistique de l'arborescence.

[NOTE]
====
* L' `-stats`option imprime un rapport lisible sur la console. Les autres options de format de rapport sont `-html` ou `-csv`. Le format CSV (valeurs séparées par des virgules) possède des valeurs exactes. Si un catalogue existe, les rapports CSV et HTML sont automatiquement enregistrés dans le catalogue.
* Les rapports XCP (.csv, .html) sont enregistrés dans l'emplacement de catalogue spécifié dans `xcp.ini` le fichier. Les fichiers sont stockés dans le `<catalog path>/catalog/indexes/1/reports` dossier. Vous pouvez afficher des exemples de rapports dans le link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886872["Référence NetApp XCP 1.9.3"^].


====
.Syntaxe
[source, cli]
----
xcp scan -stats <ip_address>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -stats <ip_address>:/fg1

Job ID: Job_2023-11-23_23.23.33.930501_scan
== Maximum Values ==
Size Used Depth File Path Namelen Dirsize
50.4 MiB 50.6 MiB 1 24 20 33
== Average Values ==
Size Depth Namelen Dirsize
15.3 MiB 0 6 33
== Top Space Users ==
root
107 MiB
== Top File Owners ==
root
34
== Top File Extensions ==
.sh .out .py .sh1 other
8 2 2 1 20
16.0 KiB 3.09 MiB 448 1.48 KiB 502 MiB
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
20 1 2 10
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
76 KiB 12 KiB 5.16 MiB 102 MiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K

== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
34
== Accessed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
33
505 MiB
== Modified ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Changed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Path ==
0-1024 >1024
33
Total count: 34
Directories: 1
Regular files: 33
Symbolic links: None
Special files: None
Hard links: None
Multilink files: None
Space Saved by Hard links (KB): 0
Sparse data: N/A
Dedupe estimate: N/A
Total space for regular files: size: 505 MiB, used: 107 MiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 8 KiB, used: 8 KiB
Total space used: 107 MiB
Xcp command : xcp scan -stats <ip_address>:/fg1
Stats : 34 scanned
Speed : 6.35 KiB in (7.23 KiB/s), 444 out (506/s)
Total Time : 0s.
Job ID : Job_2023-11-23_23.23.33.930501_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/
Job_2023-11-23_23.23.33.930501_scan.log

STATUS : PASSED
[root@client 1 linux]#


----
====
.Syntaxe
[source, cli]
----
xcp scan -csv <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -csv <IP address or hostname of NFS server>:/source_vol

scan <IP address or hostname of NFS server>:/source_vol
options,"{'-csv': True}"
summary,"13 scanned, 3.73 KiB in (11.3 KiB/s), 756 out (2.23 KiB/s), 0s."
Maximum Values,Size,Used,Depth,Namelen,Dirsize
Maximum Values,1024,4096,2,10,5
Average Values,Namelen,Size,Depth,Dirsize
Average Values,6,1024,1,4
Top Space Users,root
Top Space Users,53248
Top File Owners,root
Top File Owners,13
Top File Extensions,other
Top File Extensions,10
Number of files,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Number of files,0,10,0,0,0,0,0
Space used,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Space used,0,40960,0,0,0,0,0
Directory entries,empty,1-10,10-100,100-1K,1K-10K,>10K
Directory entries,0,3,0,0,0,0
Depth,0-5,6-10,11-15,16-20,21-100,>100
Depth,13,0,0,0,0,0
Accessed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Accessed,0,0,0,0,0,10,0
Modified,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Modified,0,0,0,0,0,10,0
Changed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Changed,0,0,0,0,0,10,0

Total count,13
Directories,3
Regular files,10
Symbolic links,0
Special files,0
Hard links,0,
multilink files,0,
Space Saved by Hard links (KB),0
Sparse data,N/A
Dedupe estimate,N/A
Total space for regular files,size,10240,used,40960
Total space for symlinks,size,0,used,0
Total space for directories,size,12288,used,12288
Total space used,53248
Xcp command : xcp scan -csv <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (11.2 KiB/s), 756 out (2.22 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====
.Syntaxe
[source, cli]
----
xcp scan -html <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -html <IP address or hostname of NFS server>:/source_vol

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<html><head>
[redacted HTML contents]
</body></html>
Xcp command : xcp scan -html <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.31 KiB/s), 756 out(873/s)
Total Time : 0s.
STATUS : PASSED
[root@localhost source_vol]#
----
====


== scan -non-ames

Utilisez le `-nonames` paramètre avec le `scan` commande permettant d'exclure les noms d'utilisateur et de groupe des listes de fichiers ou des rapports.


NOTE: Lorsqu'il est utilisé avec le `scan` commande, le `-nonames` le paramètre s'applique uniquement aux listes de fichiers renvoyées à l'aide du `-l` option.

.Syntaxe
[source, cli]
----
xcp scan -nonames <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -nonames <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -nonames <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.66 KiB/s), 756 out(944/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -newid <name>

Utilisez le `-newid <name>` paramètre avec le `scan` commande permettant de spécifier le nom du catalogue pour un nouvel index lors de l'exécution d'une analyse.

.Syntaxe
[source, cli]
----
xcp scan -newid <name> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol

Xcp command : xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 13.8 KiB in (17.7 KiB/s), 53.1 KiB out (68.0 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -id <catalog_name>

Utilisez le `-id` paramètre avec le `scan` pour spécifier le nom du catalogue de la copie précédente ou de l'index de numérisation.

.Syntaxe
[source, cli]
----
xcp scan -id <catalog_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -id 3

xcp: Index: {source: 10.10.1.10:/vol/ex_s01/etc/keymgr, target: None}
keymgr/root/cacert.pem
keymgr/cert/secureadmin.pem
keymgr/key/secureadmin.pem
keymgr/csr/secureadmin.pem
keymgr/root
keymgr/csr
keymgr/key
keymgr/cert
keymgr
9 reviewed, 11.4 KiB in (11.7 KiB/s), 1.33 KiB out (1.37 KiB/s), 0s.
----
====


== scan -match <filter>

Utilisez le `-match <filter>` paramètre avec le `scan` pour spécifier que seuls les fichiers et répertoires correspondant à un filtre sont traités.

.Syntaxe
[source, cli]
----
xcp scan -match <filter> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -match bin <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Filtered: 0 did not match
Xcp command : xcp scan -match bin <IP address or hostname of NFSserver>:/source_vol
18 scanned, 18 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -fmt <string_expression>

Utilisez le `-fmt` paramètre avec le `scan` pour spécifier que seuls les fichiers et répertoires correspondant au format spécifié sont renvoyés.

.Syntaxe
[source, cli]
----
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -fmt "'{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime)"
<IP address or hostname of NFS server>:/source_vol

source_vol, <IP address or hostname of NFS server>:/source_vol, 1583294484.46, 1583294492.63,
1583294484.46
ILE_1, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_1, 1583293637.88,
1583293637.83, 1583293637.83
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_2, 1583293637.88,
1583293637.83, 1583293637.84
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_3, 1583293637.88,
1583293637.84, 1583293637.84
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_4, 1583293637.88,
1583293637.84, 1583293637.84
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_5, 1583293637.88,
1583293637.84, 1583293637.84
file1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file1.txt, 1583294284.78,
1583294284.78, 1583294284.78
file2.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file2.txt, 1583294284.78,
1583294284.78, 1583294284.78
logfile.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/logfile.txt,
1583294295.79, 1583294295.79, 1583294295.79
log1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/log1.txt, 1583294295.8,
1583294295.8, 1583294295.8
r1.txt, <IP address or hostname of NFS server>:/source_vol/r1.txt, 1583294484.46, 1583294484.45,
1583294484.45
USER.1, <IP address or hostname of NFS server>:/source_vol/USER.1, 1583294295.8, 1583294492.63,
1583294295.8
USER.2, <IP address or hostname of NFS server>:/source_vol/USER.2, 1583293637.95, 1583294492.63,
1583293637.95
FILE_1, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_1, 1583293637.95,
1583293637.94, 1583293637.94
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_5, 1583293637.96,
1583293637.94, 1583293637.94
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_2, 1583293637.96,
1583293637.95, 1583293637.95
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_3, 1583293637.96,
1583293637.95, 1583293637.95
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_4, 1583293637.96,
1583293637.95, 1583293637.96
Xcp command : xcp scan -fmt '{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime) <IP address
or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (4.14 KiB/s), 756 out (683/s)
Total Time : 1s.
STATUS : PASSED
----
====


== scan -du

Utilisez le `-du` paramètre avec le `scan` pour résumer l'utilisation de l'espace de chaque répertoire, y compris les sous-répertoires.

.Syntaxe
[source, cli]
----
xcp scan -du <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -du <IP address or hostname of NFSserver>:/source_vol

24KiB source_vol/USER.1
24KiB source_vol/USER.2
52KiB source_vol
Xcp command : xcp scan -du <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (12.9 KiB/s), 756 out (2.07KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -md5 <string_expression>

Utilisez le `-md5` paramètre avec le `scan` commande permettant de générer des checksums pour les listes de fichiers et d'enregistrer les sommes de contrôle lors de l'indexation. La valeur par défaut est FALSE.


NOTE: Les checksums ne sont pas utilisés pour la vérification des fichiers ; ils ne sont utilisés que pour les listes de fichiers pendant les opérations d'analyse.

.Syntaxe
[source, cli]
----
xcp scan -md5 <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -md5 <IP address or hostname of NFSserver>:/source_vol

source_vol
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_4
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_5
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file1.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file2.txt
d41d8cd98f00b204e9800998ecf8427esource_vol/USER.1/logfile.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/log1.txt
e894f2344aaa92289fb57bc8f597ffa9 source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_5
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_4
Xcp command : xcp scan -md5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (34.5 KiB/s), 2.29 KiB out (4.92 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== <n> de profondeur d'acquisition

Utilisez le `-depth <n>` paramètre avec le `scan` pour limiter la profondeur de recherche d'une acquisition. Le `-depth <n>` Paramètre spécifie la profondeur dans les sous-répertoires que XCP peut analyser des fichiers. Par exemple, si le nombre 2 est spécifié, XCP analyse uniquement les deux premiers niveaux de sous-répertoire.

.Syntaxe
[source, cli]
----
xcp scan -depth <n> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -depth 2 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -depth 2 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -dircount <n[k]>

Utilisez le `-dircount <n[k]>` paramètre avec le `scan` commande permettant de spécifier la taille de la demande lors de la lecture de répertoires dans un scan. La valeur par défaut est 64k.

.Syntaxe
[source, cli]
----
xcp scan -dircount <n[k]> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -dircount 64k <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
----
====


== scan -edupe

Utilisez le `-edupe` paramètre avec le `scan` pour inclure l'estimation de la déduplication dans les rapports.


NOTE: Simple Storage Service (S3) ne prend pas en charge les fichiers peu volumineux. Par conséquent, en spécifiant un compartiment S3 comme destination cible pour `scan -edupe` Renvoie la valeur « aucun » pour les données éparses.

.Syntaxe
[source, cli]
----
xcp scan -edupe <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol

== Maximum Values ==
Size Used Depth Namelen Dirsize
1 KiB 4 KiB 2 11 9
== Average Values ==
Namelen Size Depth Dirsize
6 682 1 5
== Top Space Users ==
root
52 KiB
== Top File Owners ==
root
18
== Top File Extensions ==
.txt other
5 10
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
    4 11
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
40 KiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K
3
== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
18
== Accessed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour
4
<15 mins
11
future
== Modified ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
15
== Changed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
                                     15
Total count: 18
Directories: 3
Regular files: 15
Symbolic links: None
Special files: None
Hard links: None,
multilink files: None,
Space Saved by Hard links (KB): 0
Sparse data: None
Dedupe estimate: N/A
Total space for regular files: size: 10.0 KiB, used: 40 KiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 12 KiB, used: 12 KiB
Total space used: 52 KiB
Xcp command : xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (52.7 KiB/s), 2.29 KiB out (7.52 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -bs <n[k]>

Utilisez le `-bs <n[k]>` paramètre avec le `scan` pour spécifier la taille des blocs de lecture/écriture. Cela s'applique aux acquisitions qui lisent des données à l'aide de `-md5` ou `-edupe` paramètres. La taille de bloc par défaut est de 64 Ko.

.Syntaxe
[source, cli]
----
xcp scan -bs <n[k]> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -bs 32 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -bs 32 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (19.0 KiB/s), 756 out (3.06KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan - <n> parallèle

Utilisez le `-parallel` paramètre avec le `scan` pour spécifier le nombre maximal de traitements par lots simultanés. La valeur par défaut est 7.

.Syntaxe
[source, cli]
----
xcp scan -parallel <n> <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (7.36 KiB/s), 756 out (1.19 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan -noid

Utilisez le `-noId` paramètre avec le `scan` pour désactiver la création d'un index par défaut. La valeur par défaut est FALSE.

.Syntaxe
[source, cli]
----
xcp scan -noId <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -noId <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -noId <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (5.84 KiB/s), 756 out(963/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan -subdir-names

Utilisez le `-subdir-names` paramètre avec le `scan` commande permettant de récupérer les noms des sous-répertoires de niveau supérieur dans un répertoire.

.Syntaxe
[source, cli]
----
xcp scan -subdir-names <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol

source_vol
Xcp command : xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol
7 scanned, 0 matched, 0 error
Speed : 1.30 KiB in (1.21 KiB/s), 444 out(414/s)
Total Time : 1s.
STATUS : PASSED
----
====


== scan -preserve-atime

Utilisez le `-preserve-atime` paramètre avec le `scan` pour restaurer tous les fichiers à la date de dernier accès sur la source.

Lors de l'analyse d'un partage NFS, le temps d'accès est modifié sur les fichiers si le système de stockage est configuré pour modifier le temps d'accès en lecture. XCP ne modifie pas directement le temps d'accès. XCP lit les fichiers un par un et cela déclenche une mise à jour du temps d'accès. Le `-preserve-atime` Cette option réinitialise le temps d'accès à la valeur d'origine définie avant l'opération de lecture XCP.

.Syntaxe
[source, cli]
----
xcp scan -preserve-atime <ip_address_or_hostname>:/source_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client 1 linux]# ./xcp scan -preserve-atime 101.10.10.10:/source_vol

xcp: Job ID: Job_2022-06-30_14.14.15.334173_scan
source_vol/USER2/DIR1_4/FILE_DIR1_4_1024_1
source_vol/USER2/DIR1_4/FILE_DIR1_4_13926_4
source_vol/USER2/DIR1_4/FILE_DIR1_4_65536_2
source_vol/USER2/DIR1_4/FILE_DIR1_4_7475_3
source_vol/USER2/DIR1_4/FILE_DIR1_4_20377_5
source_vol/USER2/DIR1_4/FILE_DIR1_4_26828_6
source_vol/USER2/DIR1_4/FILE_DIR1_4_33279_7
source_vol/USER2/DIR1_4/FILE_DIR1_4_39730_8
source_vol/USER1
source_vol/USER2
source_vol/USER1/FILE_USER1_1024_1
source_vol/USER1/FILE_USER1_65536_2
source_vol/USER1/FILE_USER1_7475_3
source_vol/USER1/FILE_USER1_13926_4
source_vol/USER1/FILE_USER1_20377_5
source_vol/USER1/FILE_USER1_26828_6
source_vol/USER1/FILE_USER1_33279_7
source_vol/USER1/FILE_USER1_39730_8
source_vol/USER1/DIR1_2
source_vol/USER1/DIR1_3
source_vol/USER2/FILE_USER2_1024_1
source_vol/USER2/FILE_USER2_65536_2
source_vol/USER2/FILE_USER2_7475_3
source_vol/USER2/FILE_USER2_13926_4
source_vol/USER2/FILE_USER2_20377_5
source_vol/USER2/FILE_USER2_26828_6
source_vol/USER2/FILE_USER2_33279_7
source_vol/USER2/FILE_USER2_39730_8
source_vol/USER2/DIR1_3
source_vol/USER2/DIR1_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_1024_1
source_vol/USER1/DIR1_2/FILE_DIR1_2_7475_3
source_vol/USER1/DIR1_2/FILE_DIR1_2_33279_7
source_vol/USER1/DIR1_2/FILE_DIR1_2_26828_6
source_vol/USER1/DIR1_2/FILE_DIR1_2_65536_2
source_vol/USER1/DIR1_2/FILE_DIR1_2_39730_8
source_vol/USER1/DIR1_2/FILE_DIR1_2_13926_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER1/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER1/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER1/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER1/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER1/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER1/DIR1_3/FILE_DIR1_3_39730_8
source_vol/USER2/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER2/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER2/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER2/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER2/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER2/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER2/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER2/DIR1_3/FILE_DIR1_3_39730_8
source_vol
Xcp command : xcp scan -preserve-atime 101.10.10.10:/source_vol
Stats : 55 scanned
Speed : 14.1 KiB in (21.2 KiB/s), 2.33 KiB out (3.51 KiB/s)
Total Time : 0s.
Job ID : Job_2022-06-30_14.14.15.334173_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2022-06-30_14.14.15.334173_scan.log
STATUS : PASSED
----
====


== acquisition -s3.insecure

Utilisez le `-s3.insecure` paramètre avec le `scan` Commande permettant d'utiliser HTTP au lieu de HTTPS pour les communications entre les compartiments S3.

.Syntaxe
[source, cli]
----
xcp scan -s3.insecure s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.insecure s3://bucket1

Job ID: Job_2023-06-08_08.16.31.345201_scan
file5g_1
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.insecure s3:// -bucket1
Stats : 8 scanned, 6 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-08_08.16.31.345201_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.16.31.345201_scan.log
STATUS : PASSED
----
====


== scan -s3.<s3_endpoint_url> de terminal

Utilisez le `-s3.endpoint <s3_endpoint_url>` paramètre avec le `scan` Commande permettant de remplacer l'URL du terminal AWS par défaut par une URL spécifiée pour la communication du compartiment S3.

.Syntaxe
[source, cli]
----
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing

Job ID: Job_2023-06-13_11.23.06.029137_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
Job ID : Job_2023-06-13_11.23.06.029137_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.23.06.029137_scan.log
STATUS : PASSED
----
====


== scanner -s3.profile <name>

Utilisez le `s3.profile` paramètre avec le `scan` Commande permettant de spécifier un profil à partir du fichier d'informations d'identification AWS pour les communications du compartiment S3

.Syntaxe
[source, cli]
----
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>:
s3://bucket1

Job ID: Job_2023-06-08_08.47.11.963479_scan
1 scanned, 0 in (0/s), 0 out (0/s), 5s
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>: s3://bucket1
Stats : 7 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 6s.
Job ID : Job_2023-06-08_08.47.11.963479_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.47.11.963479_scan.log
STATUS : PASSED
[root@client1 linux]#
----
====


== acquisition -s3.noverify

Utilisez le `-s3.noverify` paramètre avec le `scan` Commande permettant de remplacer la vérification par défaut de la certification SSL pour les communications de compartiment S3.

.Syntaxe
[source, cli]
----
xcp scan -s3.noverify s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -s3.noverify s3:// bucket1

Job ID: Job_2023-06-13_11.00.59.742237_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.noverify s3://bucket1
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-13_11.00.59.742237_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.00.59.742237_scan.log
STATUS : PASSED
----
====