---
sidebar: sidebar 
permalink: xcp-environment-variable.html 
keywords: netapp, xcp, configure, configuring, how, performing, tuning, nfs, enviroment, 
summary: 'Variable d"environnement (NFS uniquement)' 
---
= Variable d'environnement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configuration de variable d'environnement facultative pour les systèmes XCP NFS.


NOTE: Un utilisateur non-root peut également utiliser les variables suivantes.

Variable d'environnement `XCP_CONFIG_DIR` remplace l'emplacement par défaut, `/opt/NetApp/xFiles/xcp`. Si elle est définie, la valeur doit correspondre à un chemin du système de fichiers du système d'exploitation, éventuellement à un répertoire NFS monté. Lorsque le `XCP_CONFIG_DIR` variable est défini, un nouveau répertoire portant le même nom que le nom d'hôte est créé dans le chemin du répertoire de configuration personnalisé, les nouveaux journaux sont stockés à cet emplacement.

[listing]
----
[root@localhost /]# export XCP_CONFIG_DIR ='/tmp/xcp_config_dir_path'
----
Variable d'environnement `XCP_LOG_DIR` Remplace l'emplacement par défaut qui stocke le journal XCP dans le répertoire de configuration. Si elle est définie, la valeur doit correspondre à un chemin du système de fichiers du système d'exploitation, éventuellement à un répertoire NFS monté. Lorsque le  `XCP_LOG_DIR` variable est défini, un nouveau répertoire avec le même nom que l'hôte est créé dans le chemin du répertoire de journaux personnalisé, les nouveaux journaux sont stockés à cet emplacement.

[listing]
----
[root@localhost /]# export XCP_LOG_DIR='/tmp/xcp_log_dir_path'
----
Variable d'environnement `XCP_CATALOG_PATH` remplace le paramètre dans xcp.ini. Si elle est définie, la valeur doit être au format de chemin xcp, `server:export[:subdirectory]`.

[listing]
----
[root@localhost /]# export XCP_CATALOG_PATH='10.61.82.210:/vol/xcpvol/'
----

NOTE: Pour un utilisateur non-racine, vous devez remplacer `XCP_CATALOG_PATH` À partir du chemin exporté avec le chemin POSIX.
