---
sidebar: sidebar 
permalink: xcp-nfs-reference-copy.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Référence de commande XCP NFS 
---
= copier
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le NFS XCP `copy` La commande analyse et copie l'ensemble de la structure du répertoire source dans une exportation NFSv3 de destination.

Le `copy` la commande nécessite l'utilisation de chemins source et de destination comme variables. Les fichiers numérisés et copiés, le débit, la vitesse et le temps écoulé sont affichés à la fin de l'opération de copie.

[NOTE]
====
* Le fichier journal d'exécution se trouve dans `/opt/NetApp/xFiles/xcp/xcp.log` Ce chemin est configurable. Une journalisation supplémentaire se trouve dans le catalogue après l'exécution de chaque commande.
* Si la source est un système 7-mode, vous pouvez utiliser une copie Snapshot comme source. Par exemple : `<ip_address>:/vol/ex_s01/.snapshot/<snapshot_name>`


====
.Syntaxe
[source, cli]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp copy <IP address of NFS server>:/source_vol < IP address of
destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.46.33.153705
Xcp command : xcp copy <IP address of NFS server>:/source_vol <IP address of destination NFS
server>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 38.9 KiB in (51.2 KiB/s), 81.2 KiB out (107KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====
Le tableau suivant répertorie la `copy` paramètres et leur description.

[cols="2*"]
|===
| Paramètre | Description 


| <<copier -non-noms>> | Exclut les noms d'utilisateur et de groupe des listes de fichiers et des rapports. 


| <<copy_match,copie - correspondance  lt;filtre  gt;  | Traite uniquement les fichiers et répertoires correspondant au filtre. 


| <<copy_md5,copy -md5  >> | Génère des sommes de contrôle sur les fichiers et enregistre les sommes de contrôle lors de l'indexation (valeur par défaut : FALSE). 


| <<copy_dircount,copy -dircount [k]>  | Spécifie la taille de la demande lors de la lecture des répertoires. 


| <<copy_edupe,copier -edupe>> | Inclut l'estimation de la déduplication dans les rapports. 


| <<copy_bs,copy -bs [k]>  | Spécifie la taille du bloc de lecture/écriture (par défaut : 64 ko). 


| <<copy_parallel,copie -parallèle  >> | Spécifie le nombre maximal de processus de traitement par lots simultanés (par défaut : 7). 


| <<copy_preserve_atime,copier -conserver-atime>> | Restaure tous les fichiers à la dernière date d'accès sur la source. 


| <<copy_s3_insecure,copie -s3.insecure>> | Permet d'utiliser HTTP au lieu de HTTPS pour les communications entre compartiments S3. 


| <<copy_s3_endpoint,copie -s3.endpoint > | Remplace l'URL du terminal Amazon Web Services (AWS) par défaut par l'URL spécifiée pour la communication du compartiment S3. 


| <<copy_s3_profile,copier -s3.profile > | Spécifie un profil à partir du fichier d'informations d'identification AWS pour la communication du compartiment S3. 


| <<copy_s3_noverify,copie -s3.noverify>> | Remplace la vérification par défaut de la certification SSL pour les communications de compartiment S3. 
|===


== copier -non-noms

Utilisez le `-nonames` paramètre avec le `copy` commande permettant d'exclure les noms d'utilisateur et de groupe des listes de fichiers ou des rapports.

.Syntaxe
[source, cli]
----
xcp copy -nonames <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -nonames <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.48.48.147261
Xcp command : xcp copy -nonames <IP address or hostname of NFS server>:/source_vol <IP address of
destination NFS server>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 38.9 KiB in (53.5 KiB/s), 81.3 KiB out (112 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== <filter> de correspondance de copie

Utilisez le `-match <filter>` paramètre avec le `copy` pour spécifier que seuls les fichiers et répertoires correspondant à un filtre sont traités.

.Syntaxe
[source, cli]
----
xcp copy -match <filter> <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -match bin <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
04_00.00.07.125990
Xcp command : xcp copy -match bin <IP address or hostname of NFS server>:/source_vol <IP address
of destination NFS server>:/dest_vol
18 scanned, 18 matched, 17 copied, 0 error
Speed : 39.1 KiB in (52.6 KiB/s), 81.7 KiB out (110 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== copie -md5 <string_expression>

Utilisez le `-md5` paramètre avec le `copy` commande permettant de générer des checksums pour les listes de fichiers et d'enregistrer les sommes de contrôle lors de l'indexation. La valeur par défaut est FALSE.

.Syntaxe
[source, cli]
----
xcp copy -md5 <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -md5 <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.47.41.137615
Xcp command : xcp copy -md5 <IP address or hostname of NFS server>:/source_vol <IP address of
destination NFS server>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 38.9 KiB in (52.1 KiB/s), 81.3 KiB out (109 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== copy -dircount <n[k]>

Utilisez le `-dircount <n[k]>` paramètre avec le `copy` commande permettant de spécifier la taille de la demande lors de la lecture des répertoires. La valeur par défaut est 64k.

.Syntaxe
[source, cli]
----
xcp copy -dircount <n[k]> <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -dircount 32k <IP address or hostname of NFS server>:/source_vol
<IP address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.58.01.094460
Xcp command : xcp copy -dircount 32k <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server >:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 39.1 KiB in (56.7 KiB/s), 81.6 KiB out (119 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== copier -edupe

Utilisez le `-edupe` paramètre avec le `copy` pour inclure l'estimation de la déduplication dans les rapports.


NOTE: Simple Storage Service (S3) ne prend pas en charge les fichiers peu volumineux. Par conséquent, en spécifiant un compartiment S3 comme destination cible pour `copy -edupe` Renvoie la valeur « aucun » pour les données éparses.

.Syntaxe
[source, cli]
----
xcp copy -edupe <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -edupe <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.48.10.436325
== Maximum Values ==
Size Used Depth Namelen Dirsize
1 KiB 4 KiB 2 11 9
== Average Values ==
Namelen Size Depth Dirsize
6 682 1 5
== Top Space Users ==
root
52 KiB
== Top File Owners ==
root
18
== Top File Extensions ==
.txt other
5 10
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
4 11
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
40 KiB
== Directory entries ==
empty 1-10
3
10-100 100-1K 1K-10K >10K
== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
18
== Accessed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
4 11
== Modified ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
10 5
== Changed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
10 5
Total count: 18
Directories: 3
Regular files: 15
Symbolic links: None
Special files: None
Hard links: None,
multilink files: None,
Space Saved by Hard links (KB): 0
Sparse data: None
Dedupe estimate: N/A
Total space for regular files: size: 10.0 KiB, used: 40 KiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 12 KiB, used: 12 KiB
Total space used: 52 KiB
Xcp command : xcp copy -edupe <IP address or hostname of NFS server>:/source_vol <destination NFS
export path>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 38.9 KiB in (36.7 KiB/s), 81.3 KiB out (76.7 KiB/s)
Total Time : 1s.
STATUS : PASSED
----
====


== copie -bs <n[k]>

Utilisez le `-bs <n[k]>` paramètre avec le `copy` pour spécifier la taille des blocs de lecture/écriture. La taille de bloc par défaut est de 64 Ko.

.Syntaxe
[source, cli]
----
xcp copy -bs <n[k]> <ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -bs 32k <IP address or hostname of NFS server>:/source_vol <IP
address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.57.04.742145
Xcp command : xcp copy -bs 32k <IP address or hostname of NFS server>:/source_vol <IP address of
destination NFS server>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 39.1 KiB in (115 KiB/s), 81.6 KiB out (241 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== copie -<n> parallèle

Utilisez le `-parallel <n>` paramètre avec le `copy` pour spécifier le nombre maximal de traitements par lots simultanés. La valeur par défaut est 7.

.Syntaxe
[source, cli]
----
xcp copy -parallel <n> <ip_address_or_hostname>:/source_vol destination_ip_address_or_hostname:/<dest_vol>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp copy -parallel 4 <IP address or hostname of NFS server>:/source_vol
<IP address of destination NFS server>:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: autoname_copy_2020-03-
03_23.59.41.477783
Xcp command : xcp copy -parallel 4 <IP address or hostname of NFS server>:/source_vol <IP address
of destination NFS server>:/dest_vol
18 scanned, 0 matched, 17 copied, 0 error
Speed : 39.1 KiB in (35.6 KiB/s), 81.6 KiB out (74.4 KiB/s)
Total Time : 1s.
STATUS : PASSED
----
====


== copier -conserver-atime

Utilisez le `-preserve-atime` paramètre avec le `copy` pour restaurer tous les fichiers à la date de dernier accès sur la source.

Le `-preserve-atime` Cette option réinitialise le temps d'accès à la valeur d'origine définie avant l'opération de lecture XCP.

.Syntaxe
[source, cli]
----
xcp copy -preserve-atime <source_ip_address_or_hostname>:/source_vol <destination_ip_address_or_hostname>:/dest_vol
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp copy -preserve-atime 101.10.10.10:/source_vol 10.102.102.10:/dest_vol

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2022-06-
30_14.22.53.742272
xcp: Job ID: Job_XCP_copy_2022-06-30_14.22.53.742272_2022-06-30_14.22.53.742272_copy
Xcp command : xcp copy -preserve-atime 101.10.10.10:/source_vol 10.102.102.10:/dest_vol
Stats : 55 scanned, 54 copied, 55 indexed
Speed : 1.26 MiB in (852 KiB/s), 1.32 MiB out (896 KiB/s)
Total Time : 1s.
Migration ID: XCP_copy_2022-06-30_14.22.53.742272
Job ID : Job_XCP_copy_2022-06-30_14.22.53.742272_2022-06-30_14.22.53.742272_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2022-06-30_14.22.53.742272_2022-06-
30_14.22.53.742272_copy.log
STATUS : PASSED
[root@client1 linux]#
----
====


== copie -s3.insecure

Utilisez le `-s3.insecure` paramètre avec le `copy` Commande permettant d'utiliser HTTP au lieu de HTTPS pour les communications entre les compartiments S3.

.Syntaxe
[source, cli]
----
xcp copy -s3.insecure s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp copy -s3.insecure hdfs:///user/test s3://bucket1

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
08_09.01.47.581599
Job ID: Job_XCP_copy_2023-06-08_09.01.47.581599_copy
Xcp command : xcp copy -s3.insecure hdfs:///user/test s3://bucket1
Stats : 8 scanned, 5 copied, 8 indexed, 5 KiB s3.data.uploaded, 5
s3.copied.single.key.file, 5 s3.copied.file
Speed : 6.78 KiB in (1.86 KiB/s), 83.3 KiB out (22.9 KiB/s)
Total Time : 3s.
Migration ID: XCP_copy_2023-06-08_09.01.47.581599
Job ID : Job_XCP_copy_2023-06-08_09.01.47.581599_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-08_09.01.47.581599_copy.log
STATUS : PASSED

[root@client1 linux]# ./xcp copy -s3.insecure hdfs:///user/demo s3://bucket1

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
08_09.15.58.807485
Job ID: Job_XCP_copy_2023-06-08_09.15.58.807485_copy
Xcp command : xcp copy -s3.insecure hdfs:///user/demo s3://bucket1
Stats : 8 scanned, 5 copied, 8 indexed, 5 KiB s3.data.uploaded, 5
s3.copied.single.key.file, 5 s3.copied.file
Speed : 10.4 KiB in (3.60 KiB/s), 85.3 KiB out (29.6 KiB/s)
Total Time : 2s.
Migration ID: XCP_copy_2023-06-08_09.15.58.807485
Job ID : Job_XCP_copy_2023-06-08_09.15.58.807485_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-08_09.15.58.807485_copy.log
STATUS : PASSED
----
====


== copie -s3.<s3_endpoint_url> de terminal

Utilisez le `-s3.endpoint <s3_endpoint_url>` paramètre avec le `copy` Commande permettant de remplacer l'URL du terminal AWS par défaut par une URL spécifiée pour la communication du compartiment S3.

.Syntaxe
[source, cli]
----
xcp copy -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/test
s3://xcp-testing

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_11.20.32.571348
Job ID: Job_XCP_copy_2023-06-13_11.20.32.571348_copy
Xcp command : xcp copy -s3.endpoint https://<endpoint_url> hdfs:///user/test s3://xcp-testing
Stats : 8 scanned, 5 copied, 8 indexed, 5 KiB s3.data.uploaded, 5
s3.copied.single.key.file, 5 s3.copied.file
Speed : 6.78 KiB in (1.77 KiB/s), 83.6 KiB out (21.8 KiB/s)
Total Time : 3s.
Migration ID: XCP_copy_2023-06-13_11.20.32.571348
Job ID : Job_XCP_copy_2023-06-13_11.20.32.571348_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_11.20.32.571348_copy.log
STATUS : PASSED
[root@client1 linux]# ./xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/demo
s3://xcp-testing

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_11.40.26.913130
Job ID: Job_XCP_copy_2023-06-13_11.40.26.913130_copy
15,009 scanned, 1,462 copied, 9 indexed, 1.46 MiB s3.data.uploaded, 1,491
s3.copied.single.key.file, 1,491 s3.copied.file, 4.58 MiB in (933 KiB/s), 1.72 MiB out (350
KiB/s), 5s
15,009 scanned, 4,283 copied, 9 indexed, 4.20 MiB s3.data.uploaded, 4,302
s3.copied.single.key.file, 4,302 s3.copied.file, 7.70 MiB in (629 KiB/s), 4.85 MiB out (632
KiB/s), 10s
15,009 scanned, 7,323 copied, 9 indexed, 7.17 MiB s3.data.uploaded, 7,343
s3.copied.single.key.file, 7,343 s3.copied.file, 11.0 MiB in (672 KiB/s), 8.24 MiB out (681
KiB/s), 15s
15,009 scanned, 10,427 copied, 9 indexed, 10.2 MiB s3.data.uploaded, 10,439
s3.copied.single.key.file, 10,439 s3.copied.file, 14.5 MiB in (690 KiB/s), 11.7 MiB out (695
KiB/s), 20s
15,009 scanned, 13,445 copied, 9 indexed, 13.1 MiB s3.data.uploaded, 13,454
s3.copied.single.key.file, 13,454 s3.copied.file, 17.8 MiB in (676 KiB/s), 15.0 MiB out (682
KiB/s), 25s
Xcp command : xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/demo s3://xcp-testing
Stats : 15,009 scanned, 15,005 copied, 15,009 indexed, 14.7 MiB s3.data.uploaded, 15,005
s3.copied.single.key.file, 15,005 s3.copied.file
Speed : 19.2 MiB in (712 KiB/s), 17.1 MiB out (635 KiB/s)
Total Time : 27s.
Migration ID: XCP_copy_2023-06-13_11.40.26.913130
Job ID : Job_XCP_copy_2023-06-13_11.40.26.913130_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_11.40.26.913130_copy.log
STATUS : PASSED
----
====


== copie -s3.profile <name>

Utilisez le `s3.profile` paramètre avec le `copy` Commande permettant de spécifier un profil à partir du fichier d'informations d'identification AWS pour les communications du compartiment S3

.Syntaxe
[source, cli]
----
xcp copy -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/test
s3://xcp-testing

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_11.20.32.571348
Job ID: Job_XCP_copy_2023-06-13_11.20.32.571348_copy
Xcp command : xcp copy -s3.endpoint https://<endpoint_url> hdfs:///user/test s3://xcp-testing
Stats : 8 scanned, 5 copied, 8 indexed, 5 KiB s3.data.uploaded, 5
s3.copied.single.key.file, 5 s3.copied.file
Speed : 6.78 KiB in (1.77 KiB/s), 83.6 KiB out (21.8 KiB/s)
Total Time : 3s.
Migration ID: XCP_copy_2023-06-13_11.20.32.571348
Job ID : Job_XCP_copy_2023-06-13_11.20.32.571348_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_11.20.32.571348_copy.log
STATUS : PASSED
[root@client1 linux]# ./xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/demo
s3://xcp-testing

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_11.40.26.913130
Job ID: Job_XCP_copy_2023-06-13_11.40.26.913130_copy
15,009 scanned, 1,462 copied, 9 indexed, 1.46 MiB s3.data.uploaded, 1,491
s3.copied.single.key.file, 1,491 s3.copied.file, 4.58 MiB in (933 KiB/s), 1.72 MiB out (350
KiB/s), 5s
15,009 scanned, 4,283 copied, 9 indexed, 4.20 MiB s3.data.uploaded, 4,302
s3.copied.single.key.file, 4,302 s3.copied.file, 7.70 MiB in (629 KiB/s), 4.85 MiB out (632
KiB/s), 10s
15,009 scanned, 7,323 copied, 9 indexed, 7.17 MiB s3.data.uploaded, 7,343
s3.copied.single.key.file, 7,343 s3.copied.file, 11.0 MiB in (672 KiB/s), 8.24 MiB out (681
KiB/s), 15s
15,009 scanned, 10,427 copied, 9 indexed, 10.2 MiB s3.data.uploaded, 10,439
s3.copied.single.key.file, 10,439 s3.copied.file, 14.5 MiB in (690 KiB/s), 11.7 MiB out (695
KiB/s), 20s
15,009 scanned, 13,445 copied, 9 indexed, 13.1 MiB s3.data.uploaded, 13,454
s3.copied.single.key.file, 13,454 s3.copied.file, 17.8 MiB in (676 KiB/s), 15.0 MiB out (682
KiB/s), 25s
Xcp command : xcp copy -s3.endpoint https://<endpoint_url>: hdfs:///user/demo s3://xcp-testing
Stats : 15,009 scanned, 15,005 copied, 15,009 indexed, 14.7 MiB s3.data.uploaded, 15,005
s3.copied.single.key.file, 15,005 s3.copied.file
Speed : 19.2 MiB in (712 KiB/s), 17.1 MiB out (635 KiB/s)
Total Time : 27s.
Migration ID: XCP_copy_2023-06-13_11.40.26.913130
Job ID : Job_XCP_copy_2023-06-13_11.40.26.913130_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_11.40.26.913130_copy.log
STATUS : PASSED
----
====


== copie -s3.noverify

Utilisez le `-s3.noverify` paramètre avec le `copy` Commande permettant de remplacer la vérification par défaut de la certification SSL pour les communications de compartiment S3.

.Syntaxe
[source, cli]
----
xcp copy -s3.noverify s3://<bucket_name>
----
.Montrer l'exemple
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp copy -s3.noverify hdfs://user/test s3:// bucket1

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_10.57.41.994969
Job ID: Job_XCP_copy_2023-06-13_10.57.41.994969_copy
Xcp command : xcp copy -s3.noverify hdfs://user/test s3://bucket1
Stats : 8 scanned, 5 copied, 8 indexed, 5 KiB s3.data.uploaded, 5
s3.copied.single.key.file, 5 s3.copied.file
Speed : 6.78 KiB in (2.36 KiB/s), 83.3 KiB out (29.0 KiB/s)
Total Time : 2s.
Migration ID: XCP_copy_2023-06-13_10.57.41.994969
Job ID : Job_XCP_copy_2023-06-13_10.57.41.994969_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_10.57.41.994969_copy.log
STATUS : PASSED
./xcp copy -s3.profile sg -s3.noverify -s3.endpoint https://<endpoint_url>: hdfs:///user/demo s3://bucket1

xcp: WARNING: No index name has been specified, creating one with name: XCP_copy_2023-06-
13_11.26.56.143287
Job ID: Job_XCP_copy_2023-06-13_11.26.56.143287_copy
1 scanned, 9.95 KiB in (1.99 KiB/s), 12.9 KiB out (2.58 KiB/s), 5s
15,009 scanned, 1,555 copied, 9 indexed, 1.54 MiB s3.data.uploaded, 1,572
s3.copied.single.key.file, 1,572 s3.copied.file, 4.68 MiB in (951 KiB/s), 1.81 MiB out (365
KiB/s), 10s
15,009 scanned, 4,546 copied, 9 indexed, 4.46 MiB s3.data.uploaded, 4,572
s3.copied.single.key.file, 4,572 s3.copied.file, 7.95 MiB in (660 KiB/s), 5.15 MiB out (674
KiB/s), 15s
15,009 scanned, 7,702 copied, 9 indexed, 7.53 MiB s3.data.uploaded, 7,710
s3.copied.single.key.file, 7,710 s3.copied.file, 11.5 MiB in (710 KiB/s), 8.65 MiB out (707
KiB/s), 20s
15,009 scanned, 10,653 copied, 9 indexed, 10.4 MiB s3.data.uploaded, 10,669
s3.copied.single.key.file, 10,669 s3.copied.file, 14.7 MiB in (661 KiB/s), 11.9 MiB out (670
KiB/s), 25s
15,009 scanned, 13,422 copied, 9 indexed, 13.1 MiB s3.data.uploaded, 13,428
s3.copied.single.key.file, 13,428 s3.copied.file, 17.8 MiB in (627 KiB/s), 15.0 MiB out (627
KiB/s), 30s
Xcp command : xcp copy -s3.profile sg -s3.noverify -s3.endpoint https://<endpoint_url>: hdfs:///user/demo s3://bucket1
Stats : 15,009 scanned, 15,005 copied, 15,009 indexed, 14.7 MiB s3.data.uploaded, 15,005
s3.copied.single.key.file, 15,005 s3.copied.file
Speed : 19.2 MiB in (609 KiB/s), 17.1 MiB out (543 KiB/s)
Total Time : 32s.
Migration ID: XCP_copy_2023-06-13_11.26.56.143287
Job ID : Job_XCP_copy_2023-06-13_11.26.56.143287_copy
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_XCP_copy_2023-06-13_11.26.56.143287_copy.log
STATUS : PASSED
----
====