---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: Installez ou mettez à niveau File Analytics pour SMB 
---
= Installez File Analytics pour SMB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installez ou mettez à niveau File Analytics pour SMB.

.Description de la tâche
Pour connaître la configuration système requise pour SMB, reportez-vous à la section link:xcp-install-xcp-smb.html["Installer XCP SMB"].

.Avant de commencer
* Vous devez configurer XCP File Analytics pour NFS sur une machine Linux pour utiliser le service XCP SMB.
* Assurez-vous que le service XCP est en cours d'exécution sur votre ordinateur Linux avant de commencer la configuration de XCP File Analytics sur un ordinateur Windows.




== Nouvelle installation de File Analytics pour SMB

Pour effectuer une nouvelle installation de File Analytics pour SMB, procédez comme suit.

.Étapes
. Copiez le `xcp.exe` Fichier sur votre Windows `C:` lecteur, ce binaire est disponible à l'intérieur `/xcp/windows` après avoir décompressé le `tgz` fichier.
. Téléchargez le fichier de licence XCP à partir du link:https://xcp.netapp.com/["Site XCP"^].
. Créez le dossier `C:\\NetApp\XCP` Et copiez la licence XCP à cet emplacement.
. Activer la licence XCP à l'aide de la commande suivante à l'invite de commande :  `xcp.exe activate`
. Dans l'invite de commande CLI de Windows, exécutez `xcp configure`.
. Lorsque vous y êtes invité, indiquez l'adresse IP de la machine Linux sur laquelle le serveur XCP File Analytics est configuré.
. Copiez le `server.key` et `server.crt` fichiers de `/opt/NetApp/xFiles/xcp/` (Dans la boîte Linux où XCP File Analytics est déjà configuré) `C:\NetApp\XCP`.
+
Si vous disposez d'un certificat d'autorité de certification, placez-le dans `C:\NetApp\XCP` avec le même nom et les mêmes extensions.

. Rendez-vous sur votre ordinateur Windows et exécutez `xcp listen`, Maintenant XCP File Analytics pour SMB est configuré. Laissez la fenêtre ouverte pour exécuter le service en continu.
. Lancez File Analytics sur un navigateur pris en charge : `\https://<ip address of linux>/xcp`
+
Reportez-vous à la section link:xcp-install-xcp-smb.html["Installer XCP SMB"] pour plus d'informations sur les navigateurs pris en charge.

. Sélectionnez `OK` lorsque la boîte de dialogue s'affiche.
+

NOTE: Un nouvel onglet s'ouvre. Activez les fenêtres contextuelles sur le navigateur si elles sont bloquées.

. Acceptez la politique de confidentialité de l'URL. Le message suivant s'affiche : `SMB agent is ready to use. Please refresh the analytics page`
. Affichez l'agent SMB sous la carte agents en retournant à l'onglet d'origine hébergeant l'interface graphique de XCP File Analytics et en actualisant la page.




== Mise à niveau de File Analytics pour SMB

Pour mettre à niveau l'analytique de fichiers existante pour SMB, procédez comme suit.

. Avant d'exécuter File Analytics, vérifiez que le serveur Linux sur lequel File Analytics est exécuté est également mis à niveau et que le service est en cours d'exécution.
. Dans Windows, arrêtez le service XCP existant en saisissant `CTRL-C` sur la ligne de commande.
. Remplacement `xcp.exe` avec le dernier binaire.
. Rendez-vous sur votre ordinateur Windows et exécutez `xcp listen` Pour configurer l'analytique de fichiers XCP pour SMB. Laissez la fenêtre ouverte pour exécuter le service en continu.
. Lancez File Analytics sur un navigateur pris en charge : `\https://<ip address of linux>/xcp`
+
Reportez-vous à la section link:xcp-install-xcp-smb.html["Installer XCP SMB"] pour plus d'informations sur les navigateurs pris en charge.

. Sélectionnez *OK* lorsque la boîte de dialogue s'affiche.
+

NOTE: Un nouvel onglet s'ouvre. Activez les fenêtres contextuelles sur le navigateur si elles sont bloquées.

. Acceptez la politique de confidentialité de l'URL. Le message suivant s'affiche : `SMB agent is ready to use. Please refresh the analytics page`
. Affichez l'agent SMB sous la carte agents en retournant à l'onglet d'origine hébergeant l'interface graphique de XCP File Analytics et en actualisant la page.

